### ISSUE TITLE
[Troubleshoot]: RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by charon87** [RLinf/RLinf#223]
### Problem description

我之前利用libero-10的数据集微调了openvla-oft，效果不佳，所以使用微调后的模型进行强化学习，我在24GB的3090上进行这个实验，因为显存不足修改了一点点代码，能够运行后现在遇到了问题，大概是第一次生成了非法动作 → 环境 state NaN → 第二次 forward 输出 NaN，请问这种情况是什么原因造成的？

### Configuration YAML file

[libero_10_grpo_openvlaoft.yaml](https://github.com/user-attachments/files/23229593/libero_10_grpo_openvlaoft.yaml)

### Log file

bash examples/embodiment/run_embodiment.sh libero_10_grpo_openvlaoft
Using Python at /home/jhn/anaconda3/envs/openvla-oft/bin/python
2025-10-30 16:32:05.337252: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical result
s due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.                                                                                                                                           2025-10-30 16:32:05.373885: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to regi
ster factory for plugin cuDNN when one has already been registered                                                                              2025-10-30 16:32:05.373916: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to regis
ter factory for plugin cuFFT when one has already been registered                                                                               2025-10-30 16:32:05.375073: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to re
gister factory for plugin cuBLAS when one has already been registered                                                                           2025-10-30 16:32:05.380991: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instru
ctions in performance-critical operations.                                                                                                      To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-10-30 16:32:06.117997: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'libero_10_grpo_openvlao
ft': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information          warnings.warn(msg, UserWarning)
/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longe
r change working directory at job runtime by default.                                                                                           See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
2025-10-30 16:32:09,102 INFO worker.py:1908 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
[INFO 16:32:10 RLinf] RLinf is running on a cluster with 1 node and 8 accelerators. The nodes' details are: [NodeInfo(node_rank=0, ray_id='043e6
3f086d47872d54a6805496d19be1ebb49536f49c94a328802a1', node_ip='10.12.13.63', accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, num_accelerators=8, num_cpus=64)]                                                                                                                             [INFO 16:32:10 FlexiblePlacementStrategy] 
[INFO 16:32:10 FlexiblePlacementStrategy] Using flexible placement with accelerator IDs: [[4]].
[INFO 16:32:10 FlexiblePlacementStrategy] 
[INFO 16:32:10 FlexiblePlacementStrategy] Using flexible placement with accelerator IDs: [[4]].
[INFO 16:32:10 FlexiblePlacementStrategy] 
[INFO 16:32:10 FlexiblePlacementStrategy] Using flexible placement with accelerator IDs: [[5], [6]].
[INFO 16:32:10 FlexiblePlacementStrategy] Generated 2 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id=5, accelerator
_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=2, visible_accelerators=['5'], isolate_accelerator=True), Placement(rank=1, node_id=0, node_rank=0, local_accelerator_id=6, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=1, local_world_size=2, visible_accelerators=['6'], isolate_accelerator=True)].                                                                                             [INFO 16:32:10 FlexiblePlacementStrategy] Generated 1 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id=4, accelerator
_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=1, visible_accelerators=['4'], isolate_accelerator=True)].             [INFO 16:32:10 FlexiblePlacementStrategy] Generated 1 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id=4, accelerator
_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=1, visible_accelerators=['4'], isolate_accelerator=True)].             (pid=3831567) 2025-10-30 16:32:13.265303: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different nu
merical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.                                                                                                                             (pid=3831565) 2025-10-30 16:32:13.244796: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different nu
merical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.                                                                                                                             (pid=3831565) 2025-10-30 16:32:13.279037: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Atte
mpting to register factory for plugin cuDNN when one has already been registered                                                                (pid=3831565) 2025-10-30 16:32:13.279080: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attem
pting to register factory for plugin cuFFT when one has already been registered                                                                 (pid=3831565) 2025-10-30 16:32:13.279983: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: At
tempting to register factory for plugin cuBLAS when one has already been registered                                                             (pid=3831565) 2025-10-30 16:32:13.285230: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use availa
ble CPU instructions in performance-critical operations.                                                                                        (pid=3831565) To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate c
ompiler flags.                                                                                                                                  (pid=3831569) 2025-10-30 16:32:13.292494: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different nu
merical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.                                                                                                                             (pid=3831569) 2025-10-30 16:32:13.329370: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Atte
mpting to register factory for plugin cuDNN when one has already been registered                                                                (pid=3831569) 2025-10-30 16:32:13.329402: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attem
pting to register factory for plugin cuFFT when one has already been registered                                                                 (pid=3831569) 2025-10-30 16:32:13.330455: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: At
tempting to register factory for plugin cuBLAS when one has already been registered                                                             (pid=3831569) 2025-10-30 16:32:13.336246: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use availa
ble CPU instructions in performance-critical operations.                                                                                        (pid=3831569) To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate c
ompiler flags.                                                                                                                                  (pid=3831567) 2025-10-30 16:32:13.300048: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Atte
mpting to register factory for plugin cuDNN when one has already been registered                                                                (pid=3831567) 2025-10-30 16:32:13.300077: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attem
pting to register factory for plugin cuFFT when one has already been registered                                                                 (pid=3831567) 2025-10-30 16:32:13.300998: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: At
tempting to register factory for plugin cuBLAS when one has already been registered                                                             (pid=3831567) 2025-10-30 16:32:13.306249: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use availa
ble CPU instructions in performance-critical operations.                                                                                        (pid=3831567) To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate c
ompiler flags.                                                                                                                                  (pid=3831571) 2025-10-30 16:32:13.423140: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different nu
merical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.                                                                                                                             (pid=3831571) 2025-10-30 16:32:13.461491: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Atte
mpting to register factory for plugin cuDNN when one has already been registered                                                                (pid=3831571) 2025-10-30 16:32:13.461538: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attem
pting to register factory for plugin cuFFT when one has already been registered                                                                 (pid=3831571) 2025-10-30 16:32:13.462485: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: At
tempting to register factory for plugin cuBLAS when one has already been registered                                                             (pid=3831571) 2025-10-30 16:32:13.467919: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use availa
ble CPU instructions in performance-critical operations.                                                                                        (pid=3831571) To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate c
ompiler flags.                                                                                                                                  (pid=3831565) 2025-10-30 16:32:14.000652: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(pid=3831567) 2025-10-30 16:32:14.017568: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(pid=3831569) 2025-10-30 16:32:14.120984: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(pid=3831571) 2025-10-30 16:32:14.207112: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
(EnvWorker pid=3831571) [INFO 16:32:14 NodePlacementStrategy] 
(EnvWorker pid=3831571) [INFO 16:32:14 NodePlacementStrategy] Using node placement with node IDs: [0].
(EnvWorker pid=3831571) [INFO 16:32:14 NodePlacementStrategy] Generated 1 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerat
or_id='0', accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=1, visible_accelerators=['0', '1', '2', '3', '4', '5', '6', '7'], isolate_accelerator=True)].                                                                                                    Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
Loading checkpoint shards:  25%|██▌       | 1/4 [00:03<00:10,  3.53s/it]
Loading checkpoint shards:  25%|██▌       | 1/4 [00:03<00:10,  3.53s/it]
Loading checkpoint shards:  50%|█████     | 2/4 [00:07<00:07,  3.56s/it]
Loading checkpoint shards:  50%|█████     | 2/4 [00:07<00:07,  3.59s/it]
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:10<00:03,  3.56s/it]
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:10<00:03,  3.58s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:11<00:00,  2.76s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:11<00:00,  2.79s/it]
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
Loading checkpoint shards:  25%|██▌       | 1/4 [00:03<00:10,  3.52s/it]
Loading checkpoint shards:  50%|█████     | 2/4 [00:07<00:07,  3.57s/it]
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:10<00:03,  3.57s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:11<00:00,  2.77s/it]
(EnvWorker pid=3831571) [robosuite WARNING] No private macro file found! (macros.py:53)
(EnvWorker pid=3831571) WARNING:robosuite_logs:No private macro file found!
(EnvWorker pid=3831571) [robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
(EnvWorker pid=3831571) WARNING:robosuite_logs:It is recommended to use a private macro file
(EnvWorker pid=3831571) [robosuite WARNING] To setup, run: python /home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/robosuite/sc
ripts/setup_macros.py (macros.py:55)                                                                                                            (EnvWorker pid=3831571) WARNING:robosuite_logs:To setup, run: python /home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/robosuite
/scripts/setup_macros.py                                                                                                                        (EnvWorker pid=3831571) /home/jhn/openvla-oft/LIBERO/libero/libero/benchmark/__init__.py:164: FutureWarning: You are using `torch.load` with `we
ights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.                                            (EnvWorker pid=3831571)   init_states = torch.load(init_states_path)
{
  "env": {
    "train": {
      "simulator_type": "libero",
      "task_suite_name": "libero_10",
      "auto_reset": false,
      "ignore_terminations": false,
      "max_episode_steps": 512,
      "use_rel_reward": true,
      "reward_coef": 5.0,
      "only_eval": false,
      "seed": 0,
      "num_group": 2,
      "group_size": 2,
      "use_fixed_reset_state_ids": true,
      "use_wrist_image": true,
      "num_envs": 4,
      "video_cfg": {
        "save_video": true,
        "info_on_video": true,
        "video_base_dir": "/home/jhn/openvla-oft/RLinf/logs/20251030-16:32:01/video/train"
      },
      "init_params": {
        "camera_heights": 256,
        "camera_widths": 256
      },
      "use_ordered_reset_state_ids": true
    },
    "eval": {
      "simulator_type": "libero",
      "task_suite_name": "libero_10",
      "auto_reset": true,
      "ignore_terminations": true,
      "max_episode_steps": 512,
      "use_rel_reward": true,
      "reward_coef": 5.0,
      "only_eval": true,
      "seed": 0,
      "num_group": 500,
      "group_size": 1,
      "use_fixed_reset_state_ids": true,
      "use_wrist_image": true,
      "num_envs": 500,
      "video_cfg": {
        "save_video": true,
        "info_on_video": true,
        "video_base_dir": "/home/jhn/openvla-oft/RLinf/logs/20251030-16:32:01/video/eval"
      },
      "init_params": {
        "camera_heights": 256,
        "camera_widths": 256
      }
    },
    "group_name": "EnvGroup",
    "channel": {
      "name": "env_buffer_list",
      "queue_name": "obs_buffer",
      "queue_size": 0
    },
    "enable_offload": false
  },
  "cluster": {
    "num_nodes": 1,
    "component_placement": {
      "env": 4,
      "rollout": 4,
      "actor": "5,6"
    }
  },
  "runner": {
    "task_type": "embodied",
    "logger": {
      "log_path": "/home/jhn/openvla-oft/RLinf/logs/20251030-16:32:01",
      "project_name": "RL",
      "experiment_name": "libero_10_grpo_openvlaoft",
      "logger_backends": [
        "tensorboard"
      ]
    },
    "max_epochs": 1000,
    "max_steps": -1,
    "only_eval": false,
    "val_check_interval": -1,
    "save_interval": 500,
    "seq_length": 4096,
    "max_prompt_length": 128
  },
  "algorithm": {
    "auto_reset": false,
    "ignore_terminations": false,
    "use_fixed_reset_state_ids": true,
    "normalize_advantages": true,
    "kl_penalty": "kl",
    "group_size": 2,
    "n_chunk_steps": 64,
    "n_eval_chunk_steps": 64,
    "num_group_envs": 2,
    "rollout_epoch": 2,
    "reward_type": "action_level",
    "logprob_type": "token_level",
    "entropy_type": "token_level",
    "adv_type": "grpo",
    "loss_type": "actor",
    "loss_agg_func": "token-mean",
    "kl_beta": 0.0,
    "entropy_bonus": 0,
    "clip_ratio_high": 0.28,
    "clip_ratio_low": 0.2,
    "clip_ratio_c": 3.0,
    "value_clip": 0.2,
    "huber_delta": 10.0,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "reward_coef": 5.0,
    "max_episode_steps": 512,
    "use_ordered_reset_state_ids": true,
    "sampling_params": {
      "use_greedy": false,
      "temperature_train": 1.6,
      "temperature_eval": 1.6,
      "top_k": -1,
      "top_p": 1.0,
      "repetition_penalty": 1.0
    },
    "length_params": {
      "max_new_token": null,
      "max_length": 1024,
      "min_length": 1
    },
    "filter_rewards": true,
    "rewards_lower_bound": 0.5,
    "rewards_upper_bound": 4.5
  },
  "rollout": {
    "group_name": "RolloutGroup",
    "channel": {
      "name": "env_buffer_list",
      "queue_name": "action_buffer",
      "queue_size": 0
    },
    "mode": "colocate",
    "generation_backend": "huggingface",
    "model_dir": "/home/jhn/openvla-oft/runs/openvla-7b+libero_10_no_noops+b1+lr-0.0001+lora-r32+dropout-0.0--image_aug--parallel_dec--8_acts_ch
unk--continuous_acts--L1_regression--3rd_person_img--wrist_img--proprio_state",                                                                     "enable_offload": false,
    "pipeline_stage_num": 1
  },
  "actor": {
    "group_name": "ActorGroup",
    "channel": {
      "name": "env_buffer_list",
      "queue_name": "replay_buffer",
      "queue_size": 0
    },
    "training_backend": "fsdp",
    "checkpoint_load_path": "/home/jhn/openvla-oft/runs/openvla-7b+libero_10_no_noops+b1+lr-0.0001+lora-r32+dropout-0.0--image_aug--parallel_dec
--8_acts_chunk--continuous_acts--L1_regression--3rd_person_img--wrist_img--proprio_state",                                                          "checkpoint_save_path": "/home/jhn/openvla-oft/RLinf/runs/libero_10_grpo_openvlaoft/",
    "micro_batch_size": 8,
    "global_batch_size": 16,
    "seed": 1234,
    "enable_offload": false,
    "model": {
      "model_name": "openvla_oft",
      "value_type": "action_level",
      "action_dim": 7,
      "num_action_chunks": 8,
      "use_proprio": true,
      "unnorm_key": "libero_10_no_noops",
      "center_crop": true,
      "precision": "fp16",
      "add_bias_linear": false,
      "add_qkv_bias": true,
      "vocab_size": 32000,
      "hidden_size": 4096,
      "policy_setup": "widowx_bridge",
      "add_value_head": false,
      "image_size": [
        224,
        224
      ],
      "is_lora": true,
      "lora_rank": 32,
      "use_wrist_image": true,
      "attn_implementation": "flash_attention_2",
      "low_cpu_mem_usage": true,
      "trust_remote_code": true,
      "gradient_checkpointing": true,
      "sharding_strategy": "full_shard"
    },
    "optim": {
      "lr": 2e-05,
      "value_lr": 0.003,
      "adam_beta1": 0.9,
      "adam_beta2": 0.999,
      "adam_eps": 1e-05,
      "clip_grad": 1.0
    },
    "tokenizer": {
      "tokenizer_type": "HuggingFaceTokenizer",
      "tokenizer_model": "/home/jhn/openvla-oft/runs/openvla-7b+libero_10_no_noops+b1+lr-0.0001+lora-r32+dropout-0.0--image_aug--parallel_dec--8
_acts_chunk--continuous_acts--L1_regression--3rd_person_img--wrist_img--proprio_state",                                                               "use_fast": false,
      "trust_remote_code": true,
      "padding_side": "right"
    },
    "fsdp_config": {
      "forward_prefetch": false,
      "limit_all_gathers": false,
      "backward_prefetch": null,
      "use_orig_params": false,
      "use_liger_kernel": false
    }
  },
  "reward": {
    "use_reward_model": false
  },
  "critic": {
    "use_critic_model": false
  }
}
(EmbodiedFSDPActor pid=3831565) Using LIBERO constants:
(EmbodiedFSDPActor pid=3831565)   NUM_ACTIONS_CHUNK = 8
(EmbodiedFSDPActor pid=3831565)   ACTION_DIM = 7
(EmbodiedFSDPActor pid=3831565)   PROPRIO_DIM = 8
(EmbodiedFSDPActor pid=3831565)   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
(EmbodiedFSDPActor pid=3831565) If needed, manually set the correct constants in `prismatic/vla/constants.py`!
(EmbodiedFSDPActor pid=3831567) Using LIBERO constants:
(EmbodiedFSDPActor pid=3831567)   NUM_ACTIONS_CHUNK = 8
(EmbodiedFSDPActor pid=3831567)   ACTION_DIM = 7
(EmbodiedFSDPActor pid=3831567)   PROPRIO_DIM = 8
(EmbodiedFSDPActor pid=3831567)   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
(EmbodiedFSDPActor pid=3831567) If needed, manually set the correct constants in `prismatic/vla/constants.py`!
(EmbodiedFSDPActor pid=3831565) layer_class is : LlamaDecoderLayer
(EmbodiedFSDPActor pid=3831567) layer_class is : LlamaDecoderLayer
(MultiStepRolloutWorker pid=3831569) Using LIBERO constants:
(MultiStepRolloutWorker pid=3831569)   NUM_ACTIONS_CHUNK = 8
(MultiStepRolloutWorker pid=3831569)   ACTION_DIM = 7
(MultiStepRolloutWorker pid=3831569)   PROPRIO_DIM = 8
(MultiStepRolloutWorker pid=3831569)   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
(MultiStepRolloutWorker pid=3831569) If needed, manually set the correct constants in `prismatic/vla/constants.py`!
(EnvWorker pid=3831571) [info] using task orders [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Global Step:   0%|                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Generating Rollout Epochs:   0%|          | 0/2 [00:00<?, ?it/s][00:00<?, ?it/s](MultiStepRolloutWorker pid=3831569)                            Generating Rollout Epochs:  50%|█████     | 1/2 [01:21<01:21, 81.82s/it]
Generating Rollout Epochs: 100%|██████████| 2/2 [02:49<00:00, 84.94s/it]
Global Step:   0%|                                                                                                                              
                                                                                                                     | 0/1000 [07:55<?, ?it/s, time/rollout=197, time/cal_adv_and_returns=0.0675, time/actor_training=278, time/step=476, env/success_once=0.0, env/return=0.0, env/episode_len=512.0, env/reward=0.0, rollout/rewards=0, rollout/advantages_mean=0, rollout/advantages_max=0, rollout/advantages_min=0, train/actor/approx_kl=0, train/actor/clip_fraction=0, train/actor/clipped_ratio=0, train/actor/dual_cliped_ratio=0, train/actor/grad_norm=nan, train/actor/lr=2e-5, traGlobal Step:   0%|▏                                                                                                                                                                                                                                     | 1/1000 [07:55<132:05:02, 475.98s/it, time/rollout=197, time/cal_adv_and_returns=0.0675, time/actor_training=278, time/step=476, env/success_once=0.0, env/return=0.0, env/episode_len=512.0, env/reward=0.0, rollout/rewards=0, rollout/advantages_mean=0, rollout/advantages_max=0, rollout/advantages_min=0, train/actor/approx_kl=0, train/actor/clip_fraction=0, train/actor/clipped_ratio=0, train/actor/dual_cliped_ratio=0, train/actor/grad_norm=nan, train/actor/lr=2e-5, traGenerating Rollout Epochs:   0%|          | 0/2 [00:00<?, ?it/s]0, train/loss=0](MultiStepRolloutWorker pid=3831569)                            (EmbodiedFSDPActor pid=3831565) [DEBUG] get_model_state_dict: FULL_STATE_DICT + CPU offload (rank0 only)

(MultiStepRolloutWorker pid=3831569) [DEBUG] Bad probs detected: NaN: True Neg: False Inf: False min: nan max: nan logits min: nan logits max: n
an                                                                                                                                              Exception occurred while running MultiStepRolloutWorker's function generate: exception is ray::MultiStepRolloutWorker.generate() (pid=3831569, i
p=10.12.13.63, actor_id=ae74f3700a40958a9a9fa7a401000000, repr=<rlinf.workers.rollout.hf.huggingface_worker.MultiStepRolloutWorker object at 0x7f9431e0cd00>)                                                                                                                                     File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/jhn/openvla-oft/RLinf/rlinf/scheduler/worker/worker.py", line 84, in async_func
    return await func(*args, **kwargs)
  File "/home/jhn/openvla-oft/RLinf/rlinf/workers/rollout/hf/huggingface_worker.py", line 149, in generate
    actions, result = self.predict(env_output["obs"])
  File "/home/jhn/openvla-oft/RLinf/rlinf/scheduler/worker/worker.py", line 74, in sync_func
    return func(*args, **kwargs)
  File "/home/jhn/openvla-oft/RLinf/rlinf/workers/rollout/hf/huggingface_worker.py", line 98, in predict
    actions, result = self.hf_model.predict_action_batch(
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jhn/openvla-oft/RLinf/rlinf/models/embodiment/openvla_oft_action_model.py", line 342, in predict_action_batch
    sample_flat = torch.multinomial(
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(MultiStepRolloutWorker pid=3831569) ../aten/src/ATen/native/cuda/TensorCompare.cu:110: _assert_async_cuda_kernel: block: [0,0,0], thread: [0,0,
0] Assertion `probability tensor contains either `inf`, `nan` or element < 0` failed.                                                           Generating Rollout Epochs:   0%|          | 0/2 [00:10<?, ?it/s]
Error executing job with overrides: ['runner.logger.log_path=/home/jhn/openvla-oft/RLinf/logs/20251030-16:32:01']
Traceback (most recent call last):
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jhn/openvla-oft/RLinf/examples/embodiment/train_embodied_agent.py", line 70, in <module>
    main()
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/jhn/openvla-oft/RLinf/examples/embodiment/train_embodied_agent.py", line 66, in main
    runner.run()
  File "/home/jhn/openvla-oft/RLinf/rlinf/runners/embodied_runner.py", line 120, in run
    env_metrics = self.generate_rollouts()
  File "/home/jhn/openvla-oft/RLinf/rlinf/runners/embodied_runner.py", line 77, in generate_rollouts
    env_results = env_futures.wait()
  File "/home/jhn/openvla-oft/RLinf/rlinf/scheduler/worker/worker_group.py", line 428, in wait
    self._wait_thread.join()
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
  File "/home/jhn/openvla-oft/RLinf/rlinf/scheduler/cluster.py", line 248, in signal_handler
    alive_actors = list_actors(
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/ray/util/state/api.py", line 817, in list_actors
    return StateApiClient(address=address).list(
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/ray/util/state/api.py", line 495, in list
    list_api_response = self._make_http_get_request(
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/ray/util/state/api.py", line 226, in _make_http_get_request
    response = response.json()
  File "/home/jhn/anaconda3/envs/openvla-oft/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Global Step:   0%|▏                                                                                                                             
                                                                                                        | 1/1000 [08:37<143:38:37, 517.63s/it, time/rollout=197, time/cal_adv_and_returns=0.0675, time/actor_training=278, time/step=476, env/success_once=0.0, env/return=0.0, env/episode_len=512.0, env/reward=0.0, rollout/rewards=0, rollout/advantages_mean=0, rollout/advantages_max=0, rollout/advantages_min=0, train/actor/approx_kl=0, train/actor/clip_fraction=0, train/actor/clipped_ratio=0, train/actor/dual_cliped_ratio=0, train/actor/grad_norm=nan, train/actor/lr=2e-5, train/actor/policy_loss=0, train/actor/ratio=0, train/entropy_loss=0, train/loss=0]                                                                

### Environment

python -V
Python 3.10.16

### Other reproduction info

我修改了RLinf/rlinf/hybrid_engines/fsdp/fsdp_model_manager.py的get_model_state_dict(self)和get_optimizer_state_dict(self)函数
    def get_model_state_dict(self):
        """安全导出模型参数，使用 FULL_STATE_DICT + CPU offload"""
        f_cfg = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
        with FSDP.state_dict_type(self.model, StateDictType.FULL_STATE_DICT, state_dict_config=f_cfg):
            state_dict = self.model.state_dict()

        # 仅在 rank0 保存（其他 rank 返回 None）
        if torch.distributed.get_rank() == 0:
            cpu_state_dict = {k: v.cpu() for k, v in state_dict.items()}
            torch.cuda.empty_cache()
            print("[DEBUG] get_model_state_dict: FULL_STATE_DICT + CPU offload (rank0 only)")
            return cpu_state_dict
        else:
            return None

    def get_optimizer_state_dict(self):
        """安全导出优化器参数，使用 FULL_STATE_DICT + CPU offload"""
        f_cfg = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
        o_cfg = OptimStateDictConfig(offload_to_cpu=True)
        with FSDP.state_dict_type(self.model, StateDictType.FULL_STATE_DICT,
                                  state_dict_config=f_cfg,
                                  optim_state_dict_config=o_cfg):
            state_dict = FSDP.optim_state_dict(self.model, self.optimizer)

        if torch.distributed.get_rank() == 0:
            cpu_state_dict = {
                k: (v.cpu() if torch.is_tensor(v) else v)
                for k, v in state_dict.items()
            }
            torch.cuda.empty_cache()
            print("[DEBUG] get_optimizer_state_dict: FULL_STATE_DICT + CPU offload (rank0 only)")
            return cpu_state_dict
        else:
            return None
并在RLinf/rlinf/models/embodiment/openvla_oft_action_model.py的predict_action_batch中加入debug
    def predict_action_batch(
        self,
        input_ids: torch.LongTensor = None,
        attention_mask: torch.Tensor = None,
        pixel_values: torch.FloatTensor = None,
        env_obs=None,
        calulate_logprobs=True,
        calulate_values=True,
        **kwargs,
    ) -> Tuple[np.ndarray, Dict[str, Any]]:
.......
        if do_sample:
            probs_tensor = torch.exp(
                processed_logprob_tensor
            )  # [B, act, vocab_size + 64]
            probs_flat = probs_tensor.view(
                -1, processed_logprob_tensor.shape[-1]
            )  # [B * act, vocab_size + 64]

            # === DEBUG 检查开始 ===
            if torch.isnan(probs_tensor).any() or (probs_tensor < 0).any() or torch.isinf(probs_tensor).any():
                print("[DEBUG] Bad probs detected:",
                    "NaN:", torch.isnan(probs_tensor).any().item(),
                    "Neg:", (probs_tensor < 0).any().item(),
                    "Inf:", torch.isinf(probs_tensor).any().item(),
                    "min:", probs_tensor.min().item(),
                    "max:", probs_tensor.max().item(),
                    "logits min:", processed_logits_tensor.min().item(),
                    "logits max:", processed_logits_tensor.max().item())
                torch.save(probs_tensor, "/tmp/bad_probs.pt")
            # === DEBUG 检查结束 ===

            sample_flat = torch.multinomial(
                probs_flat, num_samples=1, replacement=True
            )  # [B * act, 1]
            idxs = sample_flat.view(
                processed_logprob_tensor.shape[0], processed_logprob_tensor.shape[1]
            )  # [B, act]
        else:
            idxs = processed_logprob_tensor.argmax(dim=-1)  # [B, act]
........

### Before submitting a new issue...

- [x] Have you checked relevant issues, FAQs (https://rlinf.readthedocs.io/en/latest/rst_source/faq.html), or asked the chatbot at the top right corner of the [documentation page](https://rlinf.readthedocs.io).

**Comment by charon87** [comment]
conda list：
```
# packages in environment at /home/jhn/anaconda3/envs/openvla-oft:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
absl-py                   2.1.0                    pypi_0    pypi
accelerate                1.2.1                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohappyeyeballs          2.6.1                    pypi_0    pypi
aiohttp                   3.13.1                   pypi_0    pypi
aiohttp-cors              0.8.1                    pypi_0    pypi
aiosignal                 1.4.0                    pypi_0    pypi
aliyun-python-sdk-core    2.16.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.5                   pypi_0    pypi
altair                    5.5.0                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.8.0                    pypi_0    pypi
array-record              0.6.0                    pypi_0    pypi
asttokens                 3.0.0           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
astunparse                1.6.3                    pypi_0    pypi
async-timeout             5.0.1                    pypi_0    pypi
attrs                     24.3.0                   pypi_0    pypi
backports-strenum         1.3.1                    pypi_0    pypi
bddl                      3.5.0                    pypi_0    pypi
bitsandbytes              0.45.0                   pypi_0    pypi
brotlicffi                1.0.9.2         py310h6a678d5_1  
bzip2                     1.0.8                h5eee18b_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2025.9.9             h06a4308_0  
cachetools                5.5.2                    pypi_0    pypi
certifi                   2024.12.14               pypi_0    pypi
cffi                      1.17.1          py310h1fdaa30_1  
cfgv                      3.4.0                    pypi_0    pypi
charset-normalizer        3.4.1                    pypi_0    pypi
click                     8.1.8                    pypi_0    pypi
cloudpickle               3.1.1                    pypi_0    pypi
cmake                     3.31.4                   pypi_0    pypi
colorful                  0.5.7                    pypi_0    pypi
comm                      0.2.2              pyhd8ed1ab_1    conda-forge
contourpy                 1.3.1                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              44.0.3                   pypi_0    pypi
cuda-nvcc                 12.4.131                      0    nvidia
cycler                    0.12.1                   pypi_0    pypi
debugpy                   1.6.0           py310hd8f1fbe_0    conda-forge
decorator                 5.2.1           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
decord                    0.6.0                    pypi_0    pypi
diffusers                 0.30.3                   pypi_0    pypi
distlib                   0.3.9                    pypi_0    pypi
dlimp                     0.0.1                    pypi_0    pypi
dm-tree                   0.1.9                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docstring-parser          0.16                     pypi_0    pypi
draccus                   0.8.0                    pypi_0    pypi
easydict                  1.13                     pypi_0    pypi
egl-probe                 1.0.2                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
entrypoints               0.4             py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
etils                     1.12.0                   pypi_0    pypi
evdev                     1.9.2                    pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.2.0              pyhd8ed1ab_0    conda-forge
fairscale                 0.4.13                   pypi_0    pypi
fastapi                   0.115.6                  pypi_0    pypi
fastjsonschema            2.21.1                   pypi_0    pypi
ffmpeg-python             0.2.0                    pypi_0    pypi
ffmpy                     0.5.0                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flash-attn                2.7.3                    pypi_0    pypi
flatbuffers               25.2.10                  pypi_0    pypi
fonttools                 4.55.3                   pypi_0    pypi
frozenlist                1.8.0                    pypi_0    pypi
fsspec                    2024.2.0                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
gast                      0.6.0                    pypi_0    pypi
git-lfs                   3.7.0                h59e48b9_0    conda-forge
gitdb                     4.0.12                   pypi_0    pypi
gitpython                 3.1.44                   pypi_0    pypi
glfw                      2.8.0                    pypi_0    pypi
gmp                       6.3.0                h6a678d5_0  
gmpy2                     2.2.1           py310h5eee18b_0  
google-api-core           2.28.0                   pypi_0    pypi
google-auth               2.40.3                   pypi_0    pypi
google-auth-oauthlib      1.2.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.71.0                   pypi_0    pypi
gradio                    4.19.0                   pypi_0    pypi
gradio-client             0.10.0                   pypi_0    pypi
grpcio                    1.69.0                   pypi_0    pypi
gym                       0.26.2                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
h5py                      3.12.1                   pypi_0    pypi
httpcore                  1.0.7                    pypi_0    pypi
httpx                     0.28.1                   pypi_0    pypi
huggingface-hub           0.27.1                   pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
identify                  2.6.5                    pypi_0    pypi
idna                      3.10                     pypi_0    pypi
imageio                   2.37.0                   pypi_0    pypi
imageio-ffmpeg            0.6.0                    pypi_0    pypi
immutabledict             4.2.1                    pypi_0    pypi
importlib-metadata        8.7.0                    pypi_0    pypi
importlib-resources       6.5.2                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.20.2             pyh210e3f2_0    conda-forge
ipython                   8.36.0             pyh907856f_0    conda-forge
jedi                      0.19.2          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jinja2                    3.1.3                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9f                   h5ce9db8_0  
json-numpy                2.1.1                    pypi_0    pypi
jsonlines                 4.0.0                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2024.10.1                pypi_0    pypi
jupyter_client            7.3.4           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jupyter_core              5.7.2           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jupytext                  1.16.7                   pypi_0    pypi
keras                     2.15.0                   pypi_0    pypi
kiwisolver                1.4.8                    pypi_0    pypi
lcms2                     2.16                 hb9589c4_0  
ld_impl_linux-64          2.40                 h12ee557_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
lerc                      4.0.0                h6a678d5_0  
libclang                  18.1.1                   pypi_0    pypi
libdeflate                1.22                 h5eee18b_0  
libero                    0.1.0                     dev_0    <develop>
libffi                    3.4.4                h6a678d5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libpng                    1.6.39               h5eee18b_0  
libsodium                 1.0.18               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libtiff                   4.5.1                hffd6297_1  
libuuid                   1.41.5               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libwebp-base              1.3.2                h5eee18b_1  
libxcb                    1.17.0               h9b100fa_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
linkify-it-py             2.0.3                    pypi_0    pypi
llvmlite                  0.44.0                   pypi_0    pypi
lpips                     0.1.4                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_1  
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.10.0                   pypi_0    pypi
matplotlib-inline         0.1.7              pyhd8ed1ab_1    conda-forge
mdit-py-plugins           0.4.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
memray                    1.19.1                   pypi_0    pypi
mergedeep                 1.3.4                    pypi_0    pypi
ml-dtypes                 0.2.0                    pypi_0    pypi
mpc                       1.3.1                h5eee18b_0  
mpfr                      4.2.1                h5eee18b_0  
mpmath                    1.3.0           py310h06a4308_0  
msgpack                   1.1.2                    pypi_0    pypi
mujoco                    3.2.7                    pypi_0    pypi
multidict                 6.7.0                    pypi_0    pypi
mypy-extensions           1.1.0                    pypi_0    pypi
namex                     0.0.8                    pypi_0    pypi
narwhals                  1.21.1                   pypi_0    pypi
nbformat                  5.10.4                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
nest-asyncio              1.6.0           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
networkx                  3.2.1                    pypi_0    pypi
ninja                     1.11.1.3                 pypi_0    pypi
nltk                      3.9.1                    pypi_0    pypi
nodeenv                   1.9.1                    pypi_0    pypi
numba                     0.61.0                   pypi_0    pypi
numpy                     1.26.3                   pypi_0    pypi
nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
nvidia-ml-py              13.580.82                pypi_0    pypi
nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
nvitop                    1.5.3                    pypi_0    pypi
oauthlib                  3.3.1                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
opencensus                0.11.4                   pypi_0    pypi
opencensus-context        0.1.3                    pypi_0    pypi
opencv-python             4.11.0.86                pypi_0    pypi
openexr                   3.4.0                    pypi_0    pypi
openjpeg                  2.5.2                he7f1fd0_0  
openssl                   3.0.17               h5eee18b_0  
opentelemetry-api         1.38.0                   pypi_0    pypi
opentelemetry-exporter-prometheus 0.59b0                   pypi_0    pypi
opentelemetry-proto       1.38.0                   pypi_0    pypi
opentelemetry-sdk         1.38.0                   pypi_0    pypi
opentelemetry-semantic-conventions 0.59b0                   pypi_0    pypi
openvla-oft               0.0.1                    pypi_0    pypi
opt-einsum                3.4.0                    pypi_0    pypi
optree                    0.14.0                   pypi_0    pypi
orjson                    3.10.14                  pypi_0    pypi
oss2                      2.19.1                   pypi_0    pypi
packaging                 24.2                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
parso                     0.8.4           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pathlib                   1.0.1                    pypi_0    pypi
peft                      0.11.1                   pypi_0    pypi
pexpect                   4.9.0           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pickleshare               0.7.5           pyhd3eb1b0_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pillow                    10.2.0                   pypi_0    pypi
pip                       24.2            py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
piqa                      1.3.2                    pypi_0    pypi
platformdirs              4.3.6                    pypi_0    pypi
pluggy                    1.5.0                    pypi_0    pypi
pre-commit                4.0.1                    pypi_0    pypi
prometheus-client         0.23.1                   pypi_0    pypi
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.51             pyha770c72_0    conda-forge
propcache                 0.4.1                    pypi_0    pypi
proto-plus                1.26.1                   pypi_0    pypi
protobuf                  4.25.3                   pypi_0    pypi
psutil                    6.1.1                    pypi_0    pypi
pthread-stubs             0.3                  h0ce48e5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ptyprocess                0.7.0              pyhd3eb1b0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pure_eval                 0.2.3           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
py-spy                    0.4.1                    pypi_0    pypi
pyarrow                   19.0.0                   pypi_0    pypi
pyasn1                    0.6.1                    pypi_0    pypi
pyasn1-modules            0.4.2                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.22.0                   pypi_0    pypi
pydantic                  2.10.5                   pypi_0    pypi
pydantic-core             2.27.2                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.19.2                   pypi_0    pypi
pynput                    1.8.1                    pypi_0    pypi
pyopengl                  3.1.9                    pypi_0    pypi
pyparsing                 3.2.1                    pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0  
pytest                    8.3.4                    pypi_0    pypi
python                    3.10.16              he870216_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.9.0.post0     py310h06a4308_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-multipart          0.0.20                   pypi_0    pypi
python-xlib               0.33                     pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
pyyaml-include            1.4.1                    pypi_0    pypi
pyzmq                     23.0.0          py310h330234f_0    conda-forge
ray                       2.47.0                   pypi_0    pypi
readline                  8.2                  h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
referencing               0.35.1                   pypi_0    pypi
regex                     2024.11.6                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
requests-oauthlib         2.0.0                    pypi_0    pypi
rich                      14.2.0                   pypi_0    pypi
robomimic                 0.3.0                    pypi_0    pypi
robosuite                 1.4.1                    pypi_0    pypi
rpds-py                   0.22.3                   pypi_0    pypi
rsa                       4.9.1                    pypi_0    pypi
ruff                      0.9.1                    pypi_0    pypi
safetensors               0.5.2                    pypi_0    pypi
sapien                    2.2.1                    pypi_0    pypi
scipy                     1.15.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
sentry-sdk                2.21.0                   pypi_0    pypi
setproctitle              1.3.4                    pypi_0    pypi
setuptools                75.1.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
shellingham               1.5.4                    pypi_0    pypi
simple-parsing            0.1.7                    pypi_0    pypi
six                       1.17.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
smart-open                7.4.1                    pypi_0    pypi
smmap                     5.0.2                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
socksio                   1.0.0                    pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
stack_data                0.6.3           py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
starlette                 0.41.3                   pypi_0    pypi
sympy                     1.13.1                   pypi_0    pypi
tensorboard               2.15.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
tensorflow                2.15.0                   pypi_0    pypi
tensorflow-addons         0.23.0                   pypi_0    pypi
tensorflow-datasets       4.9.3                    pypi_0    pypi
tensorflow-estimator      2.15.0                   pypi_0    pypi
tensorflow-graphics       2021.12.3                pypi_0    pypi
tensorflow-io-gcs-filesystem 0.37.1                   pypi_0    pypi
tensorflow-metadata       1.17.2                   pypi_0    pypi
termcolor                 2.5.0                    pypi_0    pypi
textual                   6.4.0                    pypi_0    pypi
thop                      0.1.1-2209072238          pypi_0    pypi
timm                      0.9.16                   pypi_0    pypi
tk                        8.6.14               h993c535_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tokenizers                0.19.1                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.2.1                    pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
torch                     2.5.1+cu124              pypi_0    pypi
torchaudio                2.5.1+cu124              pypi_0    pypi
torchvision               0.20.1+cu124             pypi_0    pypi
tornado                   6.1             py310h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tqdm                      4.67.1                   pypi_0    pypi
traitlets                 5.14.3          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
transformers              4.40.1                   pypi_0    pypi
transforms3d              0.4.2                    pypi_0    pypi
trimesh                   4.8.3                    pypi_0    pypi
triton                    3.1.0                    pypi_0    pypi
typeguard                 2.13.3                   pypi_0    pypi
typer                     0.15.1                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
uc-micro-py               1.0.3                    pypi_0    pypi
urllib3                   2.3.0                    pypi_0    pypi
uvicorn                   0.34.0                   pypi_0    pypi
virtualenv                20.28.1                  pypi_0    pypi
wandb                     0.19.6                   pypi_0    pypi
wcwidth                   0.2.13          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
websockets                11.0.3                   pypi_0    pypi
werkzeug                  3.1.3                    pypi_0    pypi
wheel                     0.44.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wrapt                     1.14.2                   pypi_0    pypi
xllmx                     0.0.1                     dev_0    <develop>
xorg-libx11               1.8.12               h9b100fa_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xorg-libxau               1.0.12               h9b100fa_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xorg-libxdmcp             1.1.5                h9b100fa_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xorg-xorgproto            2024.1               h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.4.6                h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yarl                      1.22.0                   pypi_0    pypi
zeromq                    4.3.4                h2531618_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zipp                      3.21.0                   pypi_0    pypi
zlib                      1.2.13               hd233ad5_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zstd                      1.5.6                hc292b87_0  
```
nvidia-smi：
```
Thu Oct 30 17:16:05 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.230.02             Driver Version: 535.230.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:34:00.0 Off |                  N/A |
| 30%   27C    P8              29W / 350W |     56MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        Off | 00000000:35:00.0 Off |                  N/A |
| 70%   68C    P2             346W / 350W |   8034MiB / 24576MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce RTX 3090        Off | 00000000:36:00.0 Off |                  N/A |
| 30%   24C    P8              22W / 350W |     10MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce RTX 3090        Off | 00000000:37:00.0 Off |                  N/A |
| 30%   21C    P8              24W / 350W |     10MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce RTX 3090        Off | 00000000:9B:00.0 Off |                  N/A |
| 30%   25C    P8              24W / 350W |     12MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA GeForce RTX 3090        Off | 00000000:9C:00.0 Off |                  N/A |
| 30%   26C    P8              27W / 350W |     10MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA GeForce RTX 3090        Off | 00000000:9D:00.0 Off |                  N/A |
| 30%   30C    P8              21W / 350W |     10MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA GeForce RTX 3090        Off | 00000000:9E:00.0 Off |                  N/A |
| 67%   65C    P2             346W / 350W |   6122MiB / 24576MiB |     97%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1856      G   /usr/lib/xorg/Xorg                           36MiB |
|    0   N/A  N/A      2510      G   /usr/bin/gnome-shell                         11MiB |
|    1   N/A  N/A      1856      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A   2148567      C   python                                     8018MiB |
|    2   N/A  N/A      1856      G   /usr/lib/xorg/Xorg                            4MiB |
|    3   N/A  N/A      1856      G   /usr/lib/xorg/Xorg                            4MiB |
|    4   N/A  N/A      1856      G   /usr/lib/xorg/Xorg                            4MiB |
|    5   N/A  N/A      1856      G   /usr/lib/xorg/Xorg                            4MiB |
|    6   N/A  N/A      1856      G   /usr/lib/xorg/Xorg                            4MiB |
|    7   N/A  N/A      1856      G   /usr/lib/xorg/Xorg                            4MiB |
|    7   N/A  N/A   2148133      C   python                                     6106MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by charon87** [comment]
解决了，是模型精度的问题，换回bf16就好了
