### ISSUE TITLE
[Troubleshoot]: torch.OutOfMemoryError on 4090 GPUs

### ISSUE THREAD

**Issue by JiayinDeng** [RLinf/RLinf#255]
### Problem description

A `torch.OutOfMemoryError` is raised when running 
```bash
bash examples/embodiment/run_embodiment.sh behavior_ppo_openvlaoft
``` 
on a server equipped with 4090 GPUs. Before running the above command, another process was using the GPU,  with less than 1GB per GPU memory consumed.

## Config file (behavior_ppo_openvlaoft.yaml)
```txt
defaults:
  - env/train: behavior_r1pro
  - env/eval: behavior_r1pro
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null 
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/
    
cluster:
  num_nodes: 1
  component_placement:
    actor: 0-3
    env: 0-1
    rollout: 2-3

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "test_openvla"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 40
  seq_length: 4096
  max_prompt_length: 50

algorithm:
  auto_reset: False
  ignore_terminations: False
  use_fixed_reset_state_ids: False
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1
  n_chunk_steps: 20
  n_eval_chunk_steps: 20
  num_group_envs: 2
  rollout_epoch: 8
  reward_type: chunk_level
  logprob_type: token_level
  entropy_type: token_level

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0


  gamma: 0.99
  gae_lambda: 0.95

  # params for rollout
  sampling_params:
    use_greedy: False
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: True
  num_envs_per_gpu: 2

rollout:
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  backend: "huggingface"
  model_dir: "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/"
  precision: ${actor.model.precision}
  enable_offload: True
  pipeline_stage_num: 1

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  checkpoint_load_path: "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/"
  checkpoint_save_path: "../results"
  micro_batch_size: 2
  global_batch_size: 160
  seed: 1234
  enable_offload: True

  model:
    model_name: "openvla_oft"
    value_type: ${algorithm.reward_type}  # 'action' or 'token'
    action_dim: 23
    num_action_chunks: 8
    use_proprio: False
    unnorm_key: behavior_turn_on_radio
    center_crop: True

    precision: "bf16"
    add_bias_linear: False
    add_qkv_bias: True
    vocab_size: 32000
    hidden_size: 4096
    policy_setup: "widowx_bridge"
    add_value_head: True
    image_size: [224, 224]
    is_lora: False
    lora_rank: 32
    ckpt_path: null
    use_wrist_image: False
    num_images_in_input: 3
    attn_implementation: "flash_attention_2"
    low_cpu_mem_usage: True
    trust_remote_code: True
    gradient_checkpointing: True

  optim:
    lr: 1.0e-4
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 10.0
    critic_warmup_steps: 0

  tokenizer:
    tokenizer_type: "HuggingFaceTokenizer"
    tokenizer_model: "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/"
    use_fast: False
    trust_remote_code: True
    padding_side: "right"

  fsdp_config:                  # below are fsdp configs, for more details, see https://pytorch.org/docs/stable/fsdp.html and https://huggingface.co/docs/accelerate/package_reference/fsdp

    strategy: "fsdp"            # FSDP strategy: ["fsdp", "fsdp2"]

    # Sharding strategy: "full_shard" (shard parameters, gradients, optimizer states),
    # "shard_grad_op" (shard gradients and optimizer states only), 
    # "hybrid_shard" (combines data parallelism and model parallelism - sharding within FSDP groups, replicate across DDP groups),
    # "no_shard" (no sharding)
    sharding_strategy: "no_shard" 

    enable_gradient_accumulation: True  # if True, gradient accumulation will be enabled for FSDP/FSDP2 training, which will enhance training performance but increase memory usage.
    forward_prefetch: False             # if True, FSDP will explicitly prefetches the next upcoming all-gather while executing in the forward pass. only use with static graphs. Overlaps communication with computation to improve performance.
    limit_all_gathers: False            # if True, FSDP will synchronizes CPU threads to limit the number of concurrent all-gathers. Only affects strategies that schedule all-gathers
    backward_prefetch: null             # options are null, 'pre', 'post'. if 'pre', FSDP will prefetch the next upcoming all-gather while computing gradients. if 'post', FSDP will prefetch the next all-gather until current gradient is computed.
    use_orig_params: False              # if True, FSDP will use module's original parameters, it means it will expose nn.Module.named_parameters rather than FlatParameter
    use_liger_kernel: False             # if True, liger_kernel will be used for FSDP, note that currently supported models in RLinf are [qwen2.5, qwen2.5-vl], for more details, see liger_kernel's doc

    fsdp_size: -1               # Number of GPUs per FSDP group for hybrid sharding. -1 means use all available GPUs in a single FSDP group

    mixed_precision:            # mixed precision settings for fsdp/fsdp2
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

    amp:
      enabled: False                 # if True, automatic mixed precision (AMP) will be used in FSDP/FSDP2 training.
      precision: "bf16"              # precision for AMP, options are ["fp16" , "bf16"]
      use_grad_scaler: False         # if True, GradScaler will be used for AMP training to prevent underflow.

reward:
  use_reward_model: False

critic:
  use_critic_model: False
```

## Log file
```txt
python /data/em_ws/RLinf_ws/RLinf/examples/embodiment/train_embodied_agent.py --config-path /data/em_ws/RLinf_ws/RLinf/examples/embodiment/config/ --config-name behavior_ppo_openvlaoft runner.logger.log_path=/data/em_ws/RLinf_ws/RLinf/logs/20251112-03:06:25
2025-11-12 03:06:34.693382: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-12 03:06:34.806759: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-11-12 03:06:34.806788: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-11-12 03:06:34.811941: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-11-12 03:06:34.837351: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-12 03:06:36.601778: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'behavior_ppo_openvlaoft': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
2025-11-12 03:06:44,269	INFO worker.py:1908 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
[INFO 03:06:45 RLinf] RLinf is running on a cluster with 1 node and 8 accelerators. The nodes' details are: [NodeInfo(node_rank=0, ray_id='ecdf9803a3aa9faadf11fcaadb0085ca59fa4d1e9f54a6c07e2377d9', node_ip='XXX', accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, num_accelerators=8, num_cpus=144)]
Adding recipes of rule CookingObjectRule...
All recipes of rule CookingObjectRule imported successfully.
Adding recipes of rule CookingSystemRule...
All recipes of rule CookingSystemRule imported successfully.
Adding recipes of rule MixingToolRule...
All recipes of rule MixingToolRule imported successfully.
Adding recipes of rule ToggleableMachineRule...
All recipes of rule ToggleableMachineRule imported successfully.
Adding recipes of rule CookingPhysicalParticleRule...
All recipes of rule CookingPhysicalParticleRule imported successfully.
Adding recipes of rule CookingPhysicalParticleRule...
All recipes of rule CookingPhysicalParticleRule imported successfully.
{
  "env": {
    "train": {
      "simulator_type": "behavior",
      "auto_reset": false,
      "ignore_terminations": false,
      "use_rel_reward": true,
      "seed": 0,
      "num_group": 1,
      "group_size": 1,
      "use_fixed_reset_state_ids": false,
      "max_episode_steps": 2000,
      "max_steps": 2000,
      "only_eval": false,
      "image_size": [
        224,
        224
      ],
      "video_cfg": {
        "save_video": false,
        "info_on_video": true,
        "video_base_dir": "/data/em_ws/RLinf_ws/RLinf/logs/20251112-03:06:25/video/train"
      },
      "base_config_name": "r1pro_behavior",
      "num_envs": 1,
      "tasks": {
        "activity_task_indices": [
          0
        ],
        "task_description_path": "examples/embodiment/config/env/behavior_task.jsonl"
      },
      "omnigibson_cfg": {
        "env": {
          "device": null,
          "automatic_reset": false,
          "flatten_action_space": false,
          "flatten_obs_space": false,
          "use_external_obs": false,
          "initial_pos_z_offset": 0.1,
          "external_sensors": [
            {
              "sensor_type": "VisionSensor",
              "name": "external_sensor0",
              "relative_prim_path": "/external_sensor0",
              "modalities": [
                "rgb",
                "depth"
              ],
              "sensor_kwargs": {
                "image_height": 128,
                "image_width": 128
              },
              "position": [
                0,
                0,
                1.0
              ],
              "orientation": [
                0.707,
                0.0,
                0.0,
                0.707
              ],
              "pose_frame": "parent"
            }
          ]
        },
        "render": {
          "viewer_width": 1280,
          "viewer_height": 720
        },
        "scene": {
          "type": "InteractiveTraversableScene",
          "scene_model": "house_double_floor_lower",
          "trav_map_resolution": 0.1,
          "default_erosion_radius": 0.0,
          "trav_map_with_objects": true,
          "num_waypoints": 1,
          "waypoint_resolution": 0.2,
          "not_load_object_categories": null,
          "load_room_types": [
            "living_room",
            "kitchen"
          ],
          "load_room_instances": null,
          "seg_map_resolution": 1.0,
          "scene_source": "OG",
          "include_robots": true
        },
        "robots": [
          {
            "type": "R1Pro",
            "obs_modalities": [
              "rgb",
              "depth"
            ],
            "include_sensor_names": null,
            "exclude_sensor_names": null,
            "scale": 1.0,
            "self_collision": false,
            "action_normalize": true,
            "action_type": "continuous",
            "grasping_mode": "physical",
            "default_reset_mode": "tuck",
            "sensor_config": {
              "VisionSensor": {
                "sensor_kwargs": {
                  "image_height": 128,
                  "image_width": 128
                }
              }
            },
            "controller_config": {
              "base": {
                "name": "HolonomicBaseJointController",
                "motor_type": "velocity",
                "vel_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false
              },
              "trunk": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "arm_left": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "arm_right": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "gripper_left": {
                "name": "MultiFingerGripperController",
                "mode": "smooth",
                "command_input_limits": "default",
                "command_output_limits": "default"
              },
              "gripper_right": {
                "name": "MultiFingerGripperController",
                "mode": "smooth",
                "command_input_limits": "default",
                "command_output_limits": "default"
              }
            }
          }
        ],
        "objects": [],
        "task": {
          "type": "BehaviorTask",
          "activity_name": "picking_up_trash",
          "activity_definition_id": 0,
          "activity_instance_id": 0,
          "predefined_problem": null,
          "online_object_sampling": false,
          "debug_object_sampling": null,
          "highlight_task_relevant_objects": false,
          "use_presampled_robot_pose": true,
          "termination_config": {
            "max_steps": 500
          },
          "reward_config": {
            "r_potential": 1.0
          }
        }
      }
    },
    "eval": {
      "simulator_type": "behavior",
      "auto_reset": false,
      "ignore_terminations": false,
      "use_rel_reward": true,
      "seed": 0,
      "num_group": 1,
      "group_size": 1,
      "use_fixed_reset_state_ids": false,
      "max_episode_steps": 2000,
      "max_steps": 2000,
      "only_eval": true,
      "image_size": [
        224,
        224
      ],
      "video_cfg": {
        "save_video": true,
        "info_on_video": true,
        "video_base_dir": "/data/em_ws/RLinf_ws/RLinf/logs/20251112-03:06:25/video/eval"
      },
      "base_config_name": "r1pro_behavior",
      "num_envs": 0,
      "tasks": {
        "activity_task_indices": [
          0
        ],
        "task_description_path": "examples/embodiment/config/env/behavior_task.jsonl"
      },
      "omnigibson_cfg": {
        "env": {
          "device": null,
          "automatic_reset": false,
          "flatten_action_space": false,
          "flatten_obs_space": false,
          "use_external_obs": false,
          "initial_pos_z_offset": 0.1,
          "external_sensors": [
            {
              "sensor_type": "VisionSensor",
              "name": "external_sensor0",
              "relative_prim_path": "/external_sensor0",
              "modalities": [
                "rgb",
                "depth"
              ],
              "sensor_kwargs": {
                "image_height": 128,
                "image_width": 128
              },
              "position": [
                0,
                0,
                1.0
              ],
              "orientation": [
                0.707,
                0.0,
                0.0,
                0.707
              ],
              "pose_frame": "parent"
            }
          ]
        },
        "render": {
          "viewer_width": 1280,
          "viewer_height": 720
        },
        "scene": {
          "type": "InteractiveTraversableScene",
          "scene_model": "house_double_floor_lower",
          "trav_map_resolution": 0.1,
          "default_erosion_radius": 0.0,
          "trav_map_with_objects": true,
          "num_waypoints": 1,
          "waypoint_resolution": 0.2,
          "not_load_object_categories": null,
          "load_room_types": [
            "living_room",
            "kitchen"
          ],
          "load_room_instances": null,
          "seg_map_resolution": 1.0,
          "scene_source": "OG",
          "include_robots": true
        },
        "robots": [
          {
            "type": "R1Pro",
            "obs_modalities": [
              "rgb",
              "depth"
            ],
            "include_sensor_names": null,
            "exclude_sensor_names": null,
            "scale": 1.0,
            "self_collision": false,
            "action_normalize": true,
            "action_type": "continuous",
            "grasping_mode": "physical",
            "default_reset_mode": "tuck",
            "sensor_config": {
              "VisionSensor": {
                "sensor_kwargs": {
                  "image_height": 128,
                  "image_width": 128
                }
              }
            },
            "controller_config": {
              "base": {
                "name": "HolonomicBaseJointController",
                "motor_type": "velocity",
                "vel_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false
              },
              "trunk": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "arm_left": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "arm_right": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "gripper_left": {
                "name": "MultiFingerGripperController",
                "mode": "smooth",
                "command_input_limits": "default",
                "command_output_limits": "default"
              },
              "gripper_right": {
                "name": "MultiFingerGripperController",
                "mode": "smooth",
                "command_input_limits": "default",
                "command_output_limits": "default"
              }
            }
          }
        ],
        "objects": [],
        "task": {
          "type": "BehaviorTask",
          "activity_name": "picking_up_trash",
          "activity_definition_id": 0,
          "activity_instance_id": 0,
          "predefined_problem": null,
          "online_object_sampling": false,
          "debug_object_sampling": null,
          "highlight_task_relevant_objects": false,
          "use_presampled_robot_pose": true,
          "termination_config": {
            "max_steps": 500
          },
          "reward_config": {
            "r_potential": 1.0
          }
        }
      }
    },
    "group_name": "EnvGroup",
    "channel": {
      "name": "env_buffer_list",
      "queue_name": "obs_buffer",
      "queue_size": 0
    },
    "enable_offload": true,
    "num_envs_per_gpu": 2
  },
  "cluster": {
    "num_nodes": 1,
    "component_placement": {
      "actor": "0-3",
      "env": "0-1",
      "rollout": "2-3"
    }
  },
  "runner": {
    "task_type": "embodied",
    "logger": {
      "log_path": "/data/em_ws/RLinf_ws/RLinf/logs/20251112-03:06:25",
      "project_name": "rlinf",
      "experiment_name": "test_openvla",
      "logger_backends": [
        "tensorboard"
      ]
    },
    "max_epochs": 1000,
    "max_steps": -1,
    "only_eval": false,
    "val_check_interval": -1,
    "save_interval": 40,
    "seq_length": 4096,
    "max_prompt_length": 50
  },
  "algorithm": {
    "auto_reset": false,
    "ignore_terminations": false,
    "use_fixed_reset_state_ids": false,
    "normalize_advantages": true,
    "kl_penalty": "kl",
    "group_size": 1,
    "n_chunk_steps": 20,
    "n_eval_chunk_steps": 20,
    "num_group_envs": 1,
    "rollout_epoch": 8,
    "reward_type": "chunk_level",
    "logprob_type": "token_level",
    "entropy_type": "token_level",
    "adv_type": "gae",
    "loss_type": "actor_critic",
    "loss_agg_func": "token-mean",
    "kl_beta": 0.0,
    "entropy_bonus": 0,
    "clip_ratio_high": 0.28,
    "clip_ratio_low": 0.2,
    "clip_ratio_c": 3.0,
    "value_clip": 0.2,
    "huber_delta": 10.0,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "sampling_params": {
      "use_greedy": false,
      "temperature_train": 1.0,
      "temperature_eval": 0.6,
      "top_k": 50,
      "top_p": 1.0,
      "repetition_penalty": 1.0
    },
    "length_params": {
      "max_new_token": null,
      "max_length": 1024,
      "min_length": 1
    }
  },
  "rollout": {
    "group_name": "RolloutGroup",
    "channel": {
      "name": "env_buffer_list",
      "queue_name": "action_buffer",
      "queue_size": 0
    },
    "mode": "colocate",
    "backend": "huggingface",
    "model_dir": "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/",
    "precision": "bf16",
    "enable_offload": true,
    "pipeline_stage_num": 1
  },
  "actor": {
    "group_name": "ActorGroup",
    "channel": {
      "name": "env_buffer_list",
      "queue_name": "replay_buffer",
      "queue_size": 0
    },
    "training_backend": "fsdp",
    "checkpoint_load_path": "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/",
    "checkpoint_save_path": "../results",
    "micro_batch_size": 2,
    "global_batch_size": 160,
    "seed": 1234,
    "enable_offload": true,
    "model": {
      "model_name": "openvla_oft",
      "value_type": "chunk_level",
      "action_dim": 23,
      "num_action_chunks": 8,
      "use_proprio": false,
      "unnorm_key": "behavior_turn_on_radio",
      "center_crop": true,
      "precision": "bf16",
      "add_bias_linear": false,
      "add_qkv_bias": true,
      "vocab_size": 32000,
      "hidden_size": 4096,
      "policy_setup": "widowx_bridge",
      "add_value_head": true,
      "image_size": [
        224,
        224
      ],
      "is_lora": false,
      "lora_rank": 32,
      "ckpt_path": null,
      "use_wrist_image": false,
      "num_images_in_input": 3,
      "attn_implementation": "flash_attention_2",
      "low_cpu_mem_usage": true,
      "trust_remote_code": true,
      "gradient_checkpointing": true
    },
    "optim": {
      "lr": 0.0001,
      "value_lr": 0.003,
      "adam_beta1": 0.9,
      "adam_beta2": 0.999,
      "adam_eps": 1e-05,
      "clip_grad": 10.0,
      "critic_warmup_steps": 0
    },
    "tokenizer": {
      "tokenizer_type": "HuggingFaceTokenizer",
      "tokenizer_model": "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/",
      "use_fast": false,
      "trust_remote_code": true,
      "padding_side": "right"
    },
    "fsdp_config": {
      "strategy": "fsdp",
      "sharding_strategy": "no_shard",
      "enable_gradient_accumulation": true,
      "forward_prefetch": false,
      "limit_all_gathers": false,
      "backward_prefetch": null,
      "use_orig_params": false,
      "use_liger_kernel": false,
      "fsdp_size": -1,
      "mixed_precision": {
        "param_dtype": "bf16",
        "reduce_dtype": "bf16",
        "buffer_dtype": "bf16"
      },
      "amp": {
        "enabled": false,
        "precision": "bf16",
        "use_grad_scaler": false
      },
      "cpu_offload": false,
      "offload_pin_memory": false,
      "reshard_after_forward": true
    }
  },
  "reward": {
    "use_reward_model": false
  },
  "critic": {
    "use_critic_model": false
  }
}[INFO 03:06:49 FlexiblePlacementStrategy] 
[INFO 03:06:49 FlexiblePlacementStrategy] Using flexible placement with accelerator IDs: [[0], [1], [2], [3]].
[INFO 03:06:49 FlexiblePlacementStrategy] 
[INFO 03:06:49 FlexiblePlacementStrategy] Using flexible placement with accelerator IDs: [[0], [1]].
[INFO 03:06:49 FlexiblePlacementStrategy] 
[INFO 03:06:49 FlexiblePlacementStrategy] Using flexible placement with accelerator IDs: [[2], [3]].
[INFO 03:06:49 FlexiblePlacementStrategy] Generated 4 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id=0, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=4, visible_accelerators=['0'], isolate_accelerator=True), Placement(rank=1, node_id=0, node_rank=0, local_accelerator_id=1, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=1, local_world_size=4, visible_accelerators=['1'], isolate_accelerator=True), Placement(rank=2, node_id=0, node_rank=0, local_accelerator_id=2, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=2, local_world_size=4, visible_accelerators=['2'], isolate_accelerator=True), Placement(rank=3, node_id=0, node_rank=0, local_accelerator_id=3, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=3, local_world_size=4, visible_accelerators=['3'], isolate_accelerator=True)].
[INFO 03:06:49 FlexiblePlacementStrategy] Generated 2 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id=2, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=2, visible_accelerators=['2'], isolate_accelerator=True), Placement(rank=1, node_id=0, node_rank=0, local_accelerator_id=3, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=1, local_world_size=2, visible_accelerators=['3'], isolate_accelerator=True)].
[INFO 03:06:49 FlexiblePlacementStrategy] Generated 2 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id=0, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=2, visible_accelerators=['0'], isolate_accelerator=True), Placement(rank=1, node_id=0, node_rank=0, local_accelerator_id=1, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=1, local_world_size=2, visible_accelerators=['1'], isolate_accelerator=True)].
[36m(pid=2797301)[0m 2025-11-12 03:06:55.125144: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=2797301)[0m 2025-11-12 03:06:55.125212: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=2797301)[0m 2025-11-12 03:06:55.127273: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(pid=2797307)[0m 2025-11-12 03:06:55.149369: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=2797307)[0m 2025-11-12 03:06:55.149424: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=2797307)[0m 2025-11-12 03:06:55.151567: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(pid=2797306)[0m 2025-11-12 03:06:55.253909: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=2797306)[0m 2025-11-12 03:06:55.254117: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=2797306)[0m 2025-11-12 03:06:55.259227: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(pid=2797309)[0m 2025-11-12 03:06:55.285491: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=2797309)[0m 2025-11-12 03:06:55.285526: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=2797309)[0m 2025-11-12 03:06:55.286776: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(pid=2797313)[0m 2025-11-12 03:06:55.602185: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=2797313)[0m 2025-11-12 03:06:55.602239: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=2797313)[0m 2025-11-12 03:06:55.603987: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(pid=2797321)[0m 2025-11-12 03:06:55.746282: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=2797321)[0m 2025-11-12 03:06:55.746329: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=2797321)[0m 2025-11-12 03:06:55.748371: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(pid=2797307)[0m 2025-11-12 03:06:56.735838: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(pid=2797301)[0m 2025-11-12 03:06:56.847353: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(pid=2797306)[0m 2025-11-12 03:06:56.923380: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(pid=2797309)[0m 2025-11-12 03:06:56.946677: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(pid=2797313)[0m 2025-11-12 03:06:57.231305: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(pid=2797321)[0m 2025-11-12 03:06:57.444069: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(pid=2797312)[0m 2025-11-12 03:06:58.163123: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=2797312)[0m 2025-11-12 03:06:58.163175: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=2797312)[0m 2025-11-12 03:06:58.164733: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(pid=2797310)[0m 2025-11-12 03:06:58.275669: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=2797310)[0m 2025-11-12 03:06:58.275723: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=2797310)[0m 2025-11-12 03:06:58.277749: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(EnvWorker pid=2797313)[0m [INFO 03:06:59 NodePlacementStrategy] 
[36m(EnvWorker pid=2797313)[0m [INFO 03:06:59 NodePlacementStrategy] Using node placement with node IDs: [0].
[36m(EnvWorker pid=2797313)[0m [INFO 03:06:59 NodePlacementStrategy] Generated 1 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id='0', accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=1, visible_accelerators=['0', '1', '2', '3', '4', '5', '6', '7'], isolate_accelerator=True)].
[36m(pid=2797312)[0m 2025-11-12 03:06:59.567389: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(pid=2797310)[0m 2025-11-12 03:06:59.760292: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(EmbodiedFSDPActor pid=2797307)[0m 2025-11-12 03:07:46.766422: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
[36m(EmbodiedFSDPActor pid=2797307)[0m Skipping registering GPU devices...
[36m(EmbodiedFSDPActor pid=2797309)[0m 2025-11-12 03:07:47.391984: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
[36m(EmbodiedFSDPActor pid=2797309)[0m Skipping registering GPU devices...
[36m(EmbodiedFSDPActor pid=2797306)[0m 2025-11-12 03:07:49.049706: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
[36m(EmbodiedFSDPActor pid=2797306)[0m Skipping registering GPU devices...
[36m(EmbodiedFSDPActor pid=2797301)[0m 2025-11-12 03:07:49.678090: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
[36m(EmbodiedFSDPActor pid=2797301)[0m Skipping registering GPU devices...
[36m(EmbodiedFSDPActor pid=2797307)[0m 
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
[36m(EmbodiedFSDPActor pid=2797309)[0m 
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
[36m(EmbodiedFSDPActor pid=2797307)[0m 
Loading checkpoint shards:  25%|██▌       | 1/4 [00:05<00:17,  5.70s/it]
[36m(EmbodiedFSDPActor pid=2797306)[0m 
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
[36m(EmbodiedFSDPActor pid=2797309)[0m 
Loading checkpoint shards:  25%|██▌       | 1/4 [00:05<00:17,  5.70s/it]
[36m(EmbodiedFSDPActor pid=2797301)[0m 
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
[36m(EmbodiedFSDPActor pid=2797307)[0m 
Loading checkpoint shards:  50%|█████     | 2/4 [00:11<00:11,  5.69s/it]
[36m(EmbodiedFSDPActor pid=2797306)[0m 
Loading checkpoint shards:  25%|██▌       | 1/4 [00:05<00:17,  5.83s/it]
[36m(EmbodiedFSDPActor pid=2797309)[0m 
Loading checkpoint shards:  50%|█████     | 2/4 [00:11<00:11,  5.68s/it]
[36m(EmbodiedFSDPActor pid=2797301)[0m 
Loading checkpoint shards:  25%|██▌       | 1/4 [00:05<00:17,  5.90s/it]
[36m(EmbodiedFSDPActor pid=2797307)[0m 
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:17<00:05,  5.77s/it]
[36m(EmbodiedFSDPActor pid=2797307)[0m 
Loading checkpoint shards: 100%|██████████| 4/4 [00:18<00:00,  3.80s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:18<00:00,  4.50s/it]
[36m(EmbodiedFSDPActor pid=2797306)[0m 
Loading checkpoint shards:  50%|█████     | 2/4 [00:11<00:11,  5.80s/it]
[36m(EmbodiedFSDPActor pid=2797309)[0m 
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:17<00:05,  5.72s/it]
[36m(EmbodiedFSDPActor pid=2797301)[0m 
Loading checkpoint shards:  50%|█████     | 2/4 [00:11<00:11,  5.83s/it]
[36m(EmbodiedFSDPActor pid=2797309)[0m 
Loading checkpoint shards: 100%|██████████| 4/4 [00:17<00:00,  3.79s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:17<00:00,  4.49s/it]
[36m(EmbodiedFSDPActor pid=2797306)[0m 
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:17<00:05,  5.77s/it]
[36m(EmbodiedFSDPActor pid=2797306)[0m 
Loading checkpoint shards: 100%|██████████| 4/4 [00:18<00:00,  3.80s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:18<00:00,  4.53s/it]
[36m(EmbodiedFSDPActor pid=2797301)[0m 
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:17<00:05,  5.75s/it]
[36m(EmbodiedFSDPActor pid=2797301)[0m 
Loading checkpoint shards: 100%|██████████| 4/4 [00:18<00:00,  3.81s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:18<00:00,  4.54s/it]
[36m(MultiStepRolloutWorker pid=2797310)[0m 2025-11-12 03:11:08.140724: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
[36m(MultiStepRolloutWorker pid=2797310)[0m Skipping registering GPU devices...
[36m(MultiStepRolloutWorker pid=2797312)[0m 2025-11-12 03:11:08.181695: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
[36m(MultiStepRolloutWorker pid=2797312)[0m Skipping registering GPU devices...
[36m(MultiStepRolloutWorker pid=2797310)[0m 
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
[36m(MultiStepRolloutWorker pid=2797312)[0m 
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
[36m(MultiStepRolloutWorker pid=2797310)[0m 
Loading checkpoint shards:  25%|██▌       | 1/4 [00:05<00:16,  5.57s/it]
[36m(MultiStepRolloutWorker pid=2797312)[0m 
Loading checkpoint shards:  25%|██▌       | 1/4 [00:05<00:16,  5.56s/it]
[36m(MultiStepRolloutWorker pid=2797310)[0m 
Loading checkpoint shards:  50%|█████     | 2/4 [00:11<00:10,  5.50s/it]
[36m(MultiStepRolloutWorker pid=2797312)[0m 
Loading checkpoint shards:  50%|█████     | 2/4 [00:11<00:11,  5.54s/it]
[36m(MultiStepRolloutWorker pid=2797310)[0m 
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:16<00:05,  5.59s/it]
[36m(MultiStepRolloutWorker pid=2797312)[0m 
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:16<00:05,  5.60s/it]
[36m(MultiStepRolloutWorker pid=2797310)[0m 
Loading checkpoint shards: 100%|██████████| 4/4 [00:17<00:00,  3.70s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:17<00:00,  4.38s/it]
[36m(MultiStepRolloutWorker pid=2797312)[0m 
Loading checkpoint shards: 100%|██████████| 4/4 [00:17<00:00,  3.67s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:17<00:00,  4.37s/it]

[36m(EmbodiedFSDPActor pid=2797301)[0m [INFO 03:07:02 ActorGroup-Rank-0][fsdp_model_manager.py:98] [FSDP] AMP is disabled.
[36m(EmbodiedFSDPActor pid=2797306)[0m [INFO 03:07:02 ActorGroup-Rank-1][fsdp_model_manager.py:98] [FSDP] AMP is disabled.
[36m(EmbodiedFSDPActor pid=2797307)[0m [INFO 03:07:02 ActorGroup-Rank-2][fsdp_model_manager.py:98] [FSDP] AMP is disabled.
[36m(EmbodiedFSDPActor pid=2797309)[0m [INFO 03:07:02 ActorGroup-Rank-3][fsdp_model_manager.py:98] [FSDP] AMP is disabled.
[36m(EmbodiedFSDPActor pid=2797307)[0m Using LIBERO constants:
[36m(EmbodiedFSDPActor pid=2797307)[0m   NUM_ACTIONS_CHUNK = 8
[36m(EmbodiedFSDPActor pid=2797307)[0m   ACTION_DIM = 7
[36m(EmbodiedFSDPActor pid=2797307)[0m   PROPRIO_DIM = 8
[36m(EmbodiedFSDPActor pid=2797307)[0m   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
[36m(EmbodiedFSDPActor pid=2797307)[0m If needed, manually set the correct constants in `prismatic/vla/constants.py`!
[36m(EmbodiedFSDPActor pid=2797309)[0m Using LIBERO constants:
[36m(EmbodiedFSDPActor pid=2797309)[0m   NUM_ACTIONS_CHUNK = 8
[36m(EmbodiedFSDPActor pid=2797309)[0m   ACTION_DIM = 7
[36m(EmbodiedFSDPActor pid=2797309)[0m   PROPRIO_DIM = 8
[36m(EmbodiedFSDPActor pid=2797309)[0m   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
[36m(EmbodiedFSDPActor pid=2797309)[0m If needed, manually set the correct constants in `prismatic/vla/constants.py`!
[36m(EmbodiedFSDPActor pid=2797306)[0m Using LIBERO constants:
[36m(EmbodiedFSDPActor pid=2797306)[0m   NUM_ACTIONS_CHUNK = 8
[36m(EmbodiedFSDPActor pid=2797306)[0m   ACTION_DIM = 7
[36m(EmbodiedFSDPActor pid=2797306)[0m   PROPRIO_DIM = 8
[36m(EmbodiedFSDPActor pid=2797306)[0m   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
[36m(EmbodiedFSDPActor pid=2797306)[0m If needed, manually set the correct constants in `prismatic/vla/constants.py`!
[36m(EmbodiedFSDPActor pid=2797301)[0m Using LIBERO constants:
[36m(EmbodiedFSDPActor pid=2797301)[0m   NUM_ACTIONS_CHUNK = 8
[36m(EmbodiedFSDPActor pid=2797301)[0m   ACTION_DIM = 7
[36m(EmbodiedFSDPActor pid=2797301)[0m   PROPRIO_DIM = 8
[36m(EmbodiedFSDPActor pid=2797301)[0m   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
[36m(EmbodiedFSDPActor pid=2797301)[0m If needed, manually set the correct constants in `prismatic/vla/constants.py`!
[36m(MultiStepRolloutWorker pid=2797310)[0m Using LIBERO constants:
[36m(MultiStepRolloutWorker pid=2797310)[0m   NUM_ACTIONS_CHUNK = 8
[36m(MultiStepRolloutWorker pid=2797310)[0m   ACTION_DIM = 7
[36m(MultiStepRolloutWorker pid=2797310)[0m   PROPRIO_DIM = 8
[36m(MultiStepRolloutWorker pid=2797310)[0m   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
[36m(MultiStepRolloutWorker pid=2797310)[0m If needed, manually set the correct constants in `prismatic/vla/constants.py`!
[36m(MultiStepRolloutWorker pid=2797312)[0m Using LIBERO constants:
[36m(MultiStepRolloutWorker pid=2797312)[0m   NUM_ACTIONS_CHUNK = 8
[36m(MultiStepRolloutWorker pid=2797312)[0m   ACTION_DIM = 7
[36m(MultiStepRolloutWorker pid=2797312)[0m   PROPRIO_DIM = 8
[36m(MultiStepRolloutWorker pid=2797312)[0m   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
[36m(MultiStepRolloutWorker pid=2797312)[0m If needed, manually set the correct constants in `prismatic/vla/constants.py`!
Exception occurred while running MultiStepRolloutWorker's function init_worker: exception is [36mray::MultiStepRolloutWorker.init_worker()[39m (pid=2797310, ip=XXX, actor_id=d8d8d7dce149f2f1d133246101000000, repr=<rlinf.workers.rollout.hf.huggingface_worker.MultiStepRolloutWorker object at 0x7f2d56440610>)
  File "/data/em_ws/RLinf_ws/RLinf/rlinf/scheduler/worker/worker.py", line 70, in sync_func
    return func(*args, **kwargs)
  File "/data/em_ws/RLinf_ws/RLinf/rlinf/workers/rollout/hf/huggingface_worker.py", line 54, in init_worker
    self.hf_model = get_model(self.cfg.rollout.model_dir, self.cfg.actor.model)
  File "/data/em_ws/RLinf_ws/RLinf/rlinf/models/__init__.py", line 250, in get_model
    model = model.cuda()
  File "/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2664, in cuda
    return super().cuda(*args, **kwargs)
  File "/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1050, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in _apply
    param_applied = fn(param)
  File "/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1050, in <lambda>
    return self._apply(lambda t: t.cuda(device))
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB. GPU 0 has a total capacity of 23.64 GiB of which 264.00 MiB is free. Process 2086283 has 419.48 MiB memory in use. Including non-PyTorch memory, this process has 8.04 GiB memory in use. Process 2797307 has 14.85 GiB memory in use. Of the allocated memory 7.63 GiB is allocated by PyTorch, and 40.11 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Exiting main process due to a failure upon worker execution.
```

### Configuration YAML file

See above

### Log file

See above

### Environment

nvidia-smi
```txt
Wed Nov 12 03:22:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:4E:00.0 Off |                  Off |
| 30%   29C    P8             22W /  450W |     507MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off |   00000000:4F:00.0 Off |                  Off |
| 30%   29C    P8             21W /  450W |     459MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 4090        Off |   00000000:50:00.0 Off |                  Off |
| 32%   29C    P8             28W /  450W |     466MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GeForce RTX 4090        Off |   00000000:51:00.0 Off |                  Off |
| 33%   29C    P8             31W /  450W |     461MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA GeForce RTX 4090        Off |   00000000:CC:00.0 Off |                  Off |
| 30%   28C    P8             28W /  450W |     459MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA GeForce RTX 4090        Off |   00000000:CD:00.0 Off |                  Off |
| 30%   29C    P8             21W /  450W |     464MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA GeForce RTX 4090        Off |   00000000:CE:00.0 Off |                  Off |
| 30%   43C    P2            118W /  450W |    9559MiB /  24564MiB |     34%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA GeForce RTX 4090        Off |   00000000:CF:00.0 Off |                  Off |
| 32%   29C    P8             24W /  450W |     464MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      3367      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A   2086283    C+G   python                                        457MiB |
|    1   N/A  N/A      3367      G   /usr/lib/xorg/Xorg                              4MiB |
|    1   N/A  N/A   2086283    C+G   python                                        419MiB |
|    2   N/A  N/A      3367      G   /usr/lib/xorg/Xorg                              4MiB |
|    2   N/A  N/A   2086283    C+G   python                                        419MiB |
|    3   N/A  N/A      3367      G   /usr/lib/xorg/Xorg                              4MiB |
|    3   N/A  N/A   2086283    C+G   python                                        419MiB |
|    4   N/A  N/A      3367      G   /usr/lib/xorg/Xorg                              4MiB |
|    4   N/A  N/A   2086283    C+G   python                                        419MiB |
|    5   N/A  N/A      3367      G   /usr/lib/xorg/Xorg                              4MiB |
|    5   N/A  N/A   2086283    C+G   python                                        419MiB |
|    6   N/A  N/A      3367      G   /usr/lib/xorg/Xorg                              4MiB |
|    6   N/A  N/A   2086283    C+G   python                                       9519MiB |
|    7   N/A  N/A      3367      G   /usr/lib/xorg/Xorg                              4MiB |
|    7   N/A  N/A   2086283    C+G   python                                        419MiB |
+-----------------------------------------------------------------------------------------+
```

### Before submitting a new issue...

- [x] Have you checked relevant issues, FAQs (https://rlinf.readthedocs.io/en/latest/rst_source/faq.html), or asked the chatbot at the top right corner of the [documentation page](https://rlinf.readthedocs.io).

**Comment by JiayinDeng** [comment]
Solved by setting
```txt
actor: 1-2
env: 0-0
rollout: 3-3
```

**Comment by Chongyu-hub** [comment]
> Solved by setting
> 
> actor: 1-2
> env: 0-0
> rollout: 3-3

Could you tell me if you successfully completed the training? If the training was successful, could you share the config file?
