### ISSUE TITLE
[Troubleshoot]: Exception occurred while running EmbodiedFSDPActor's function sync_model_to_rollout.

### ISSUE THREAD

**Issue by JiayinDeng** [RLinf/RLinf#272]
### Problem description

Raise `Exception occurred while running EmbodiedFSDPActor's function sync_model_to_rollout.` and `torch.OutOfMemoryError` using the following command:
```bash
bash examples/embodiment/run_embodiment.sh behavior_ppo_openvlaof
```

To be honest, I’ve been struggling with OOM issues for the past few days. It seems this problem is caused by the actor not properly offloading GPU resources. Am I right?

### Configuration YAML file

```txt
defaults:
  - env/train: behavior_r1pro
  - env/eval: behavior_r1pro
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null 
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/
    
cluster:
  num_nodes: 1
  component_placement:
    actor: 2-2
    env: 0-0
    rollout: 1-1

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "test_openvla"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 40
  seq_length: 4096
  max_prompt_length: 50

algorithm:
  auto_reset: False
  ignore_terminations: False
  use_fixed_reset_state_ids: False
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1
  n_chunk_steps: 20
  n_eval_chunk_steps: 20
  num_group_envs: 2
  rollout_epoch: 8
  reward_type: chunk_level
  logprob_type: token_level
  entropy_type: token_level

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0


  gamma: 0.99
  gae_lambda: 0.95

  # params for rollout
  sampling_params:
    use_greedy: False
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False
  num_envs_per_gpu: 2

rollout:
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  backend: "huggingface"
  model_dir: "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/"
  precision: ${actor.model.precision}
  enable_offload: True
  pipeline_stage_num: 1

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  checkpoint_load_path: "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/"
  checkpoint_save_path: "../results"
  micro_batch_size: 1
  global_batch_size: 1
  seed: 1234
  enable_offload: True

  model:
    model_name: "openvla_oft"
    value_type: ${algorithm.reward_type}  # 'action' or 'token'
    action_dim: 23
    num_action_chunks: 8
    use_proprio: False
    unnorm_key: behavior_turn_on_radio
    center_crop: True

    precision: "bf16"
    add_bias_linear: False
    add_qkv_bias: True
    vocab_size: 32000
    hidden_size: 4096
    policy_setup: "widowx_bridge"
    add_value_head: True
    image_size: [224, 224]
    is_lora: False
    lora_rank: 32
    ckpt_path: null
    use_wrist_image: False
    num_images_in_input: 3
    attn_implementation: "flash_attention_2"
    low_cpu_mem_usage: True
    trust_remote_code: True
    gradient_checkpointing: True

  optim:
    lr: 1.0e-4
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 10.0
    critic_warmup_steps: 0

  tokenizer:
    tokenizer_type: "HuggingFaceTokenizer"
    tokenizer_model: "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/"
    use_fast: False
    trust_remote_code: True
    padding_side: "right"

  fsdp_config:                  # below are fsdp configs, for more details, see https://pytorch.org/docs/stable/fsdp.html and https://huggingface.co/docs/accelerate/package_reference/fsdp

    strategy: "fsdp"            # FSDP strategy: ["fsdp", "fsdp2"]

    # Sharding strategy: "full_shard" (shard parameters, gradients, optimizer states),
    # "shard_grad_op" (shard gradients and optimizer states only), 
    # "hybrid_shard" (combines data parallelism and model parallelism - sharding within FSDP groups, replicate across DDP groups),
    # "no_shard" (no sharding)
    sharding_strategy: "no_shard" 

    enable_gradient_accumulation: True  # if True, gradient accumulation will be enabled for FSDP/FSDP2 training, which will enhance training performance but increase memory usage.
    forward_prefetch: False             # if True, FSDP will explicitly prefetches the next upcoming all-gather while executing in the forward pass. only use with static graphs. Overlaps communication with computation to improve performance.
    limit_all_gathers: False            # if True, FSDP will synchronizes CPU threads to limit the number of concurrent all-gathers. Only affects strategies that schedule all-gathers
    backward_prefetch: null             # options are null, 'pre', 'post'. if 'pre', FSDP will prefetch the next upcoming all-gather while computing gradients. if 'post', FSDP will prefetch the next all-gather until current gradient is computed.
    use_orig_params: False              # if True, FSDP will use module's original parameters, it means it will expose nn.Module.named_parameters rather than FlatParameter
    use_liger_kernel: False             # if True, liger_kernel will be used for FSDP, note that currently supported models in RLinf are [qwen2.5, qwen2.5-vl], for more details, see liger_kernel's doc

    fsdp_size: -1               # Number of GPUs per FSDP group for hybrid sharding. -1 means use all available GPUs in a single FSDP group

    mixed_precision:            # mixed precision settings for fsdp/fsdp2
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

    amp:
      enabled: True                 # if True, automatic mixed precision (AMP) will be used in FSDP/FSDP2 training.
      precision: "bf16"              # precision for AMP, options are ["fp16" , "bf16"]
      use_grad_scaler: False         # if True, GradScaler will be used for AMP training to prevent underflow.

reward:
  use_reward_model: False

critic:
  use_critic_model: False
```

### Log file

```txt
python /data/em_ws/RLinf_ws/RLinf/examples/embodiment/train_embodied_agent.py --config-path /data/em_ws/RLinf_ws/RLinf/examples/embodiment/config/ --config-name behavior_ppo_openvlaoft runner.logger.log_path=/data/em_ws/RLinf_ws/RLinf/logs/20251113-08:04:01
2025-11-13 08:04:10.698601: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-13 08:04:10.807255: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-11-13 08:04:10.807286: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-11-13 08:04:10.816320: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-11-13 08:04:10.823910: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-13 08:04:12.674334: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'behavior_ppo_openvlaoft': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
2025-11-13 08:04:21,591	INFO worker.py:1908 -- Started a local Ray instance. View the dashboard at [1m[32m127.0.0.1:8265 [39m[22m
[INFO 08:04:22 RLinf] RLinf is running on a cluster with 1 node and 8 accelerators. The nodes' details are: [NodeInfo(node_rank=0, ray_id='afb22829f71a2919b2c63f54218aa18ba22f1d14c68c3557c9965540', node_ip='10.10.221.38', accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, num_accelerators=8, num_cpus=144)]
Adding recipes of rule CookingObjectRule...
All recipes of rule CookingObjectRule imported successfully.
Adding recipes of rule CookingSystemRule...
All recipes of rule CookingSystemRule imported successfully.
Adding recipes of rule MixingToolRule...
All recipes of rule MixingToolRule imported successfully.
Adding recipes of rule ToggleableMachineRule...
All recipes of rule ToggleableMachineRule imported successfully.
Adding recipes of rule CookingPhysicalParticleRule...
All recipes of rule CookingPhysicalParticleRule imported successfully.
Adding recipes of rule CookingPhysicalParticleRule...
All recipes of rule CookingPhysicalParticleRule imported successfully.
{
  "env": {
    "train": {
      "simulator_type": "behavior",
      "auto_reset": false,
      "ignore_terminations": false,
      "use_rel_reward": true,
      "seed": 0,
      "num_group": 2,
      "group_size": 1,
      "use_fixed_reset_state_ids": false,
      "max_episode_steps": 2000,
      "max_steps": 2000,
      "only_eval": false,
      "image_size": [
        224,
        224
      ],
      "video_cfg": {
        "save_video": false,
        "info_on_video": true,
        "video_base_dir": "/data/em_ws/RLinf_ws/RLinf/logs/20251113-08:04:01/video/train"
      },
      "base_config_name": "r1pro_behavior",
      "num_envs": 2,
      "tasks": {
        "activity_task_indices": [
          0
        ],
        "task_description_path": "examples/embodiment/config/env/behavior_task.jsonl"
      },
      "omnigibson_cfg": {
        "env": {
          "device": null,
          "automatic_reset": false,
          "flatten_action_space": false,
          "flatten_obs_space": false,
          "use_external_obs": false,
          "initial_pos_z_offset": 0.1,
          "external_sensors": [
            {
              "sensor_type": "VisionSensor",
              "name": "external_sensor0",
              "relative_prim_path": "/external_sensor0",
              "modalities": [
                "rgb",
                "depth"
              ],
              "sensor_kwargs": {
                "image_height": 128,
                "image_width": 128
              },
              "position": [
                0,
                0,
                1.0
              ],
              "orientation": [
                0.707,
                0.0,
                0.0,
                0.707
              ],
              "pose_frame": "parent"
            }
          ]
        },
        "render": {
          "viewer_width": 1280,
          "viewer_height": 720
        },
        "scene": {
          "type": "InteractiveTraversableScene",
          "scene_model": "house_double_floor_lower",
          "trav_map_resolution": 0.1,
          "default_erosion_radius": 0.0,
          "trav_map_with_objects": true,
          "num_waypoints": 1,
          "waypoint_resolution": 0.2,
          "not_load_object_categories": null,
          "load_room_types": [
            "living_room",
            "kitchen"
          ],
          "load_room_instances": null,
          "seg_map_resolution": 1.0,
          "scene_source": "OG",
          "include_robots": true
        },
        "robots": [
          {
            "type": "R1Pro",
            "obs_modalities": [
              "rgb",
              "depth"
            ],
            "include_sensor_names": null,
            "exclude_sensor_names": null,
            "scale": 1.0,
            "self_collision": false,
            "action_normalize": true,
            "action_type": "continuous",
            "grasping_mode": "physical",
            "default_reset_mode": "tuck",
            "sensor_config": {
              "VisionSensor": {
                "sensor_kwargs": {
                  "image_height": 128,
                  "image_width": 128
                }
              }
            },
            "controller_config": {
              "base": {
                "name": "HolonomicBaseJointController",
                "motor_type": "velocity",
                "vel_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false
              },
              "trunk": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "arm_left": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "arm_right": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "gripper_left": {
                "name": "MultiFingerGripperController",
                "mode": "smooth",
                "command_input_limits": "default",
                "command_output_limits": "default"
              },
              "gripper_right": {
                "name": "MultiFingerGripperController",
                "mode": "smooth",
                "command_input_limits": "default",
                "command_output_limits": "default"
              }
            }
          }
        ],
        "objects": [],
        "task": {
          "type": "BehaviorTask",
          "activity_name": "picking_up_trash",
          "activity_definition_id": 0,
          "activity_instance_id": 0,
          "predefined_problem": null,
          "online_object_sampling": false,
          "debug_object_sampling": null,
          "highlight_task_relevant_objects": false,
          "use_presampled_robot_pose": true,
          "termination_config": {
            "max_steps": 500
          },
          "reward_config": {
            "r_potential": 1.0
          }
        }
      }
    },
    "eval": {
      "simulator_type": "behavior",
      "auto_reset": false,
      "ignore_terminations": false,
      "use_rel_reward": true,
      "seed": 0,
      "num_group": 2,
      "group_size": 1,
      "use_fixed_reset_state_ids": false,
      "max_episode_steps": 2000,
      "max_steps": 2000,
      "only_eval": true,
      "image_size": [
        224,
        224
      ],
      "video_cfg": {
        "save_video": true,
        "info_on_video": true,
        "video_base_dir": "/data/em_ws/RLinf_ws/RLinf/logs/20251113-08:04:01/video/eval"
      },
      "base_config_name": "r1pro_behavior",
      "num_envs": 1,
      "tasks": {
        "activity_task_indices": [
          0
        ],
        "task_description_path": "examples/embodiment/config/env/behavior_task.jsonl"
      },
      "omnigibson_cfg": {
        "env": {
          "device": null,
          "automatic_reset": false,
          "flatten_action_space": false,
          "flatten_obs_space": false,
          "use_external_obs": false,
          "initial_pos_z_offset": 0.1,
          "external_sensors": [
            {
              "sensor_type": "VisionSensor",
              "name": "external_sensor0",
              "relative_prim_path": "/external_sensor0",
              "modalities": [
                "rgb",
                "depth"
              ],
              "sensor_kwargs": {
                "image_height": 128,
                "image_width": 128
              },
              "position": [
                0,
                0,
                1.0
              ],
              "orientation": [
                0.707,
                0.0,
                0.0,
                0.707
              ],
              "pose_frame": "parent"
            }
          ]
        },
        "render": {
          "viewer_width": 1280,
          "viewer_height": 720
        },
        "scene": {
          "type": "InteractiveTraversableScene",
          "scene_model": "house_double_floor_lower",
          "trav_map_resolution": 0.1,
          "default_erosion_radius": 0.0,
          "trav_map_with_objects": true,
          "num_waypoints": 1,
          "waypoint_resolution": 0.2,
          "not_load_object_categories": null,
          "load_room_types": [
            "living_room",
            "kitchen"
          ],
          "load_room_instances": null,
          "seg_map_resolution": 1.0,
          "scene_source": "OG",
          "include_robots": true
        },
        "robots": [
          {
            "type": "R1Pro",
            "obs_modalities": [
              "rgb",
              "depth"
            ],
            "include_sensor_names": null,
            "exclude_sensor_names": null,
            "scale": 1.0,
            "self_collision": false,
            "action_normalize": true,
            "action_type": "continuous",
            "grasping_mode": "physical",
            "default_reset_mode": "tuck",
            "sensor_config": {
              "VisionSensor": {
                "sensor_kwargs": {
                  "image_height": 128,
                  "image_width": 128
                }
              }
            },
            "controller_config": {
              "base": {
                "name": "HolonomicBaseJointController",
                "motor_type": "velocity",
                "vel_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false
              },
              "trunk": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "arm_left": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "arm_right": {
                "name": "JointController",
                "motor_type": "position",
                "pos_kp": 150,
                "command_input_limits": "default",
                "command_output_limits": "default",
                "use_impedances": false,
                "use_delta_commands": false
              },
              "gripper_left": {
                "name": "MultiFingerGripperController",
                "mode": "smooth",
                "command_input_limits": "default",
                "command_output_limits": "default"
              },
              "gripper_right": {
                "name": "MultiFingerGripperController",
                "mode": "smooth",
                "command_input_limits": "default",
                "command_output_limits": "default"
              }
            }
          }
        ],
        "objects": [],
        "task": {
          "type": "BehaviorTask",
          "activity_name": "picking_up_trash",
          "activity_definition_id": 0,
          "activity_instance_id": 0,
          "predefined_problem": null,
          "online_object_sampling": false,
          "debug_object_sampling": null,
          "highlight_task_relevant_objects": false,
          "use_presampled_robot_pose": true,
          "termination_config": {
            "max_steps": 500
          },
          "reward_config": {
            "r_potential": 1.0
          }
        }
      }
    },
    "group_name": "EnvGroup",
    "channel": {
      "name": "env_buffer_list",
      "queue_name": "obs_buffer",
      "queue_size": 0
    },
    "enable_offload": false,
    "num_envs_per_gpu": 2
  },
  "cluster": {
    "num_nodes": 1,
    "component_placement": {
      "actor": "2-2",
      "env": "0-0",
      "rollout": "1-1"
    }
  },
  "runner": {
    "task_type": "embodied",
    "logger": {
      "log_path": "/data/em_ws/RLinf_ws/RLinf/logs/20251113-08:04:01",
      "project_name": "rlinf",
      "experiment_name": "test_openvla",
      "logger_backends": [
        "tensorboard"
      ]
    },
    "max_epochs": 1000,
    "max_steps": -1,
    "only_eval": false,
    "val_check_interval": -1,
    "save_interval": 40,
    "seq_length": 4096,
    "max_prompt_length": 50
  },
  "algorithm": {
    "auto_reset": false,
    "ignore_terminations": false,
    "use_fixed_reset_state_ids": false,
    "normalize_advantages": true,
    "kl_penalty": "kl",
    "group_size": 1,
    "n_chunk_steps": 20,
    "n_eval_chunk_steps": 20,
    "num_group_envs": 2,
    "rollout_epoch": 8,
    "reward_type": "chunk_level",
    "logprob_type": "token_level",
    "entropy_type": "token_level",
    "adv_type": "gae",
    "loss_type": "actor_critic",
    "loss_agg_func": "token-mean",
    "kl_beta": 0.0,
    "entropy_bonus": 0,
    "clip_ratio_high": 0.28,
    "clip_ratio_low": 0.2,
    "clip_ratio_c": 3.0,
    "value_clip": 0.2,
    "huber_delta": 10.0,
    "gamma": 0.99,
    "gae_lambda": 0.95,
    "sampling_params": {
      "use_greedy": false,
      "temperature_train": 1.0,
      "temperature_eval": 0.6,
      "top_k": 50,
      "top_p": 1.0,
      "repetition_penalty": 1.0
    },
    "length_params": {
      "max_new_token": null,
      "max_length": 1024,
      "min_length": 1
    }
  },
  "rollout": {
    "group_name": "RolloutGroup",
    "channel": {
      "name": "env_buffer_list",
      "queue_name": "action_buffer",
      "queue_size": 0
    },
    "mode": "colocate",
    "backend": "huggingface",
    "model_dir": "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/",
    "precision": "bf16",
    "enable_offload": true,
    "pipeline_stage_num": 1
  },
  "actor": {
    "group_name": "ActorGroup",
    "channel": {
      "name": "env_buffer_list",
      "queue_name": "replay_buffer",
      "queue_size": 0
    },
    "training_backend": "fsdp",
    "checkpoint_load_path": "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/",
    "checkpoint_save_path": "../results",
    "micro_batch_size": 1,
    "global_batch_size": 1,
    "seed": 1234,
    "enable_offload": true,
    "model": {
      "model_name": "openvla_oft",
      "value_type": "chunk_level",
      "action_dim": 23,
      "num_action_chunks": 8,
      "use_proprio": false,
      "unnorm_key": "behavior_turn_on_radio",
      "center_crop": true,
      "precision": "bf16",
      "add_bias_linear": false,
      "add_qkv_bias": true,
      "vocab_size": 32000,
      "hidden_size": 4096,
      "policy_setup": "widowx_bridge",
      "add_value_head": true,
      "image_size": [
        224,
        224
      ],
      "is_lora": false,
      "lora_rank": 32,
      "ckpt_path": null,
      "use_wrist_image": false,
      "num_images_in_input": 3,
      "attn_implementation": "flash_attention_2",
      "low_cpu_mem_usage": true,
      "trust_remote_code": true,
      "gradient_checkpointing": true
    },
    "optim": {
      "lr": 0.0001,
      "value_lr": 0.003,
      "adam_beta1": 0.9,
      "adam_beta2": 0.999,
      "adam_eps": 1e-05,
      "clip_grad": 10.0,
      "critic_warmup_steps": 0
    },
    "tokenizer": {
      "tokenizer_type": "HuggingFaceTokenizer",
      "tokenizer_model": "/data/em_ws/RLinf_ws/RLinf-OpenVLAOFT-Behavior/",
      "use_fast": false,
      "trust_remote_code": true,
      "padding_side": "right"
    },
    "fsdp_config": {
      "strategy": "fsdp",
      "sharding_strategy": "no_shard",
      "enable_gradient_accumulation": true,
      "forward_prefetch": false,
      "limit_all_gathers": false,
      "backward_prefetch": null,
      "use_orig_params": false,
      "use_liger_kernel": false,
      "fsdp_size": -1,
      "mixed_precision": {
        "param_dtype": "bf16",
        "reduce_dtype": "bf16",
        "buffer_dtype": "bf16"
      },
      "amp": {
        "enabled": true,
        "precision": "bf16",
        "use_grad_scaler": false
      },
      "cpu_offload": false,
      "offload_pin_memory": false,
      "reshard_after_forward": true
    }
  },
  "reward": {
    "use_reward_model": false
  },
  "critic": {
    "use_critic_model": false
  }
}[INFO 08:04:26 FlexiblePlacementStrategy] 
[INFO 08:04:26 FlexiblePlacementStrategy] Using flexible placement with accelerator IDs: [[2]].
[INFO 08:04:26 FlexiblePlacementStrategy] 
[INFO 08:04:26 FlexiblePlacementStrategy] Using flexible placement with accelerator IDs: [[0]].
[INFO 08:04:26 FlexiblePlacementStrategy] 
[INFO 08:04:26 FlexiblePlacementStrategy] Using flexible placement with accelerator IDs: [[1]].
[INFO 08:04:26 FlexiblePlacementStrategy] Generated 1 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id=2, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=1, visible_accelerators=['2'], isolate_accelerator=True)].
[INFO 08:04:26 FlexiblePlacementStrategy] Generated 1 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id=1, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=1, visible_accelerators=['1'], isolate_accelerator=True)].
[INFO 08:04:26 FlexiblePlacementStrategy] Generated 1 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id=0, accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=1, visible_accelerators=['0'], isolate_accelerator=True)].
[36m(pid=1160063)[0m 2025-11-13 08:04:33.027845: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=1160063)[0m 2025-11-13 08:04:33.027916: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=1160063)[0m 2025-11-13 08:04:33.030647: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(pid=1160067)[0m 2025-11-13 08:04:33.105706: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=1160067)[0m 2025-11-13 08:04:33.105739: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=1160067)[0m 2025-11-13 08:04:33.108228: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(pid=1160063)[0m 2025-11-13 08:04:34.834166: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(pid=1160067)[0m 2025-11-13 08:04:34.931342: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(pid=1160065)[0m 2025-11-13 08:04:35.359226: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[36m(pid=1160065)[0m 2025-11-13 08:04:35.359277: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[36m(pid=1160065)[0m 2025-11-13 08:04:35.361965: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[36m(pid=1160065)[0m 2025-11-13 08:04:37.155720: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[36m(EnvWorker pid=1160067)[0m [INFO 08:04:37 NodePlacementStrategy] 
[36m(EnvWorker pid=1160067)[0m [INFO 08:04:37 NodePlacementStrategy] Using node placement with node IDs: [0].
[36m(EnvWorker pid=1160067)[0m [INFO 08:04:37 NodePlacementStrategy] Generated 1 placements: [Placement(rank=0, node_id=0, node_rank=0, local_accelerator_id='0', accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, local_rank=0, local_world_size=1, visible_accelerators=['0', '1', '2', '3', '4', '5', '6', '7'], isolate_accelerator=True)].
[36m(EmbodiedFSDPActor pid=1160063)[0m 2025-11-13 08:05:37.061486: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
[36m(EmbodiedFSDPActor pid=1160063)[0m Skipping registering GPU devices...
[36m(EmbodiedFSDPActor pid=1160063)[0m 
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
[36m(EmbodiedFSDPActor pid=1160063)[0m 
Loading checkpoint shards:  25%|██▌       | 1/4 [00:06<00:18,  6.26s/it]
[36m(EmbodiedFSDPActor pid=1160063)[0m 
Loading checkpoint shards:  50%|█████     | 2/4 [00:12<00:12,  6.18s/it]
[36m(EmbodiedFSDPActor pid=1160063)[0m 
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:18<00:06,  6.20s/it]
[36m(EmbodiedFSDPActor pid=1160063)[0m 
Loading checkpoint shards: 100%|██████████| 4/4 [00:19<00:00,  4.09s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:19<00:00,  4.86s/it]
[36m(MultiStepRolloutWorker pid=1160065)[0m 2025-11-13 08:08:54.683187: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
[36m(MultiStepRolloutWorker pid=1160065)[0m Skipping registering GPU devices...
[36m(MultiStepRolloutWorker pid=1160065)[0m 
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]
[36m(MultiStepRolloutWorker pid=1160065)[0m 
Loading checkpoint shards:  25%|██▌       | 1/4 [00:05<00:17,  5.71s/it]
[36m(MultiStepRolloutWorker pid=1160065)[0m 
Loading checkpoint shards:  50%|█████     | 2/4 [00:11<00:11,  5.80s/it]
[36m(MultiStepRolloutWorker pid=1160065)[0m 
Loading checkpoint shards:  75%|███████▌  | 3/4 [00:17<00:05,  5.81s/it]
[36m(MultiStepRolloutWorker pid=1160065)[0m 
Loading checkpoint shards: 100%|██████████| 4/4 [00:18<00:00,  3.79s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:18<00:00,  4.52s/it]
[36m(EnvWorker pid=1160067)[0m 
Loading environments:   0%|          | 0/2 [00:00<?, ?it/s][0m[00:06:56.994] [INFO] [omnigibson.simulator] ----- Starting OmniGibson. This will take 10-30 seconds... -----[0m
[36m(EnvWorker pid=1160067)[0m [0m[00:06:56.995] [INFO] [omnigibson.simulator] Texture cache folder found, removing...[0m
[36m(EnvWorker pid=1160067)[0m [32m[00:07:01.169] [DEBUG] [asyncio] Using selector: EpollSelector[0m

[36m(EmbodiedFSDPActor pid=1160063)[0m [INFO 08:04:46 ActorGroup-Rank-0][fsdp_model_manager.py:103] [FSDP] AMP is enabled with precision: torch.bfloat16.
[36m(EmbodiedFSDPActor pid=1160063)[0m Using LIBERO constants:
[36m(EmbodiedFSDPActor pid=1160063)[0m   NUM_ACTIONS_CHUNK = 8
[36m(EmbodiedFSDPActor pid=1160063)[0m   ACTION_DIM = 7
[36m(EmbodiedFSDPActor pid=1160063)[0m   PROPRIO_DIM = 8
[36m(EmbodiedFSDPActor pid=1160063)[0m   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
[36m(EmbodiedFSDPActor pid=1160063)[0m If needed, manually set the correct constants in `prismatic/vla/constants.py`!
[36m(MultiStepRolloutWorker pid=1160065)[0m Using LIBERO constants:
[36m(MultiStepRolloutWorker pid=1160065)[0m   NUM_ACTIONS_CHUNK = 8
[36m(MultiStepRolloutWorker pid=1160065)[0m   ACTION_DIM = 7
[36m(MultiStepRolloutWorker pid=1160065)[0m   PROPRIO_DIM = 8
[36m(MultiStepRolloutWorker pid=1160065)[0m   ACTION_PROPRIO_NORMALIZATION_TYPE = bounds_q99
[36m(MultiStepRolloutWorker pid=1160065)[0m If needed, manually set the correct constants in `prismatic/vla/constants.py`!
[36m(EnvWorker pid=1160067)[0m Starting kit application with the following args:  ['/data/em_ws/RLinf_ws/RLinf/isaac-sim/exts/isaacsim.simulation_app/isaacsim/simulation_app/simulation_app.py', '/data/em_ws/RLinf_ws/RLinf/isaac-sim/apps/omnigibson_4_5_0.kit', '--/app/tokens/exe-path=/data/em_ws/RLinf_ws/RLinf/isaac-sim/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True', '--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=False', '--/app/fastShutdown=True', '--/app/installSignalHandlers=0', '--ext-folder', '/data/em_ws/RLinf_ws/RLinf/isaac-sim/exts', '--ext-folder', '/data/em_ws/RLinf_ws/RLinf/isaac-sim/apps', '--/physics/cudaDevice=0', '--portable', '--no-window', '--/app/window/hideUi=1']
[36m(EnvWorker pid=1160067)[0m Passing the following args to the base kit application:  ['--node-ip-address=10.10.221.38', '--node-manager-port=43993', '--object-store-name=/tmp/ray/session_2025-11-13_08-04-15_821399_1148967/sockets/plasma_store', '--raylet-name=/tmp/ray/session_2025-11-13_08-04-15_821399_1148967/sockets/raylet', '--redis-address=None', '--metrics-agent-port=51185', '--logging-rotate-bytes=536870912', '--logging-rotate-backup-count=5', '--runtime-env-agent-port=52095', '--gcs-address=10.10.221.38:64398', '--session-name=session_2025-11-13_08-04-15_821399_1148967', '--temp-dir=/tmp/ray', '--webui=127.0.0.1:8265', '--cluster-id=2a8c9ae0f5379b551254f0300a8f9e7a55305c161527a30e8241bba8', '--startup-token=150', '--worker-launch-time-ms=1763021066762', '--node-id=afb22829f71a2919b2c63f54218aa18ba22f1d14c68c3557c9965540', '--runtime-env-hash=399176739', '--enable-resource-isolation=false']
[36m(EnvWorker pid=1160067)[0m [Info] [carb] Logging to file: /data/em_ws/RLinf_ws/RLinf/isaac-sim/kit/logs/Kit/OmniGibson/3.7/kit_20251113_081127.log
[36m(EnvWorker pid=1160067)[0m 2025-11-13 08:11:27 [0ms] [Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.
......
[36m(EnvWorker pid=1160067)[0m 2025-11-13 08:11:29 [2,598ms] [Warning] [gpu.foundation.plugin] Skipping NVIDIA GPU due CUDA being in bad state: NVIDIA GeForce RTX 4090
[36m(EnvWorker pid=1160067)[0m 2025-11-13 08:11:29 [2,598ms] [Warning] [gpu.foundation.plugin] Please restart your system if CUDA is known to work in your system.
[36m(EnvWorker pid=1160067)[0m 
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
[36m(EnvWorker pid=1160067)[0m | Driver Version: 550.163.01    | Graphics API: Vulkan
[36m(EnvWorker pid=1160067)[0m |=============================================================================================|
[36m(EnvWorker pid=1160067)[0m | GPU | Name                             | Active | LDA | GPU Memory | Vendor-ID | LUID       |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | Device-ID | UUID       |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | Bus-ID    |            |
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
[36m(EnvWorker pid=1160067)[0m | 0   | NVIDIA GeForce RTX 4090          | Yes: 0 |     | 24810   MB | 10de      | 0          |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 2684      | 661ca979.. |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 4e        |            |
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
[36m(EnvWorker pid=1160067)[0m | 1   | NVIDIA GeForce RTX 4090          |        |     | 24810   MB | 10de      | 0          |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 2684      | 89735cc7.. |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 4f        |            |
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
[36m(EnvWorker pid=1160067)[0m | 2   | NVIDIA GeForce RTX 4090          |        |     | 24810   MB | 10de      | 0          |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 2684      | 64d60f71.. |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 50        |            |
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
[36m(EnvWorker pid=1160067)[0m | 3   | NVIDIA GeForce RTX 4090          |        |     | 24810   MB | 10de      | 0          |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 2684      | 3dc0c693.. |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 51        |            |
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
[36m(EnvWorker pid=1160067)[0m | 4   | NVIDIA GeForce RTX 4090          |        |     | 24810   MB | 10de      | 0          |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 2684      | 9728672f.. |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | cc        |            |
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
[36m(EnvWorker pid=1160067)[0m | 5   | NVIDIA GeFor
[36m(EnvWorker pid=1160067)[0m ce RTX 4090          |        |     | 24810   MB | 10de      | 0          |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 2684      | 62ab4f14.. |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | cd        |            |
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
[36m(EnvWorker pid=1160067)[0m | 6   | NVIDIA GeForce RTX 4090          |        |     | 24810   MB | 10de      | 0          |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 2684      | 8f3f0e1a.. |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | ce        |            |
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
[36m(EnvWorker pid=1160067)[0m | 7   | NVIDIA GeForce RTX 4090          |        |     | 24810   MB | 10de      | 0          |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | 2684      | 411cb8c5.. |
[36m(EnvWorker pid=1160067)[0m |     |                                  |        |     |            | cf        |            |
[36m(EnvWorker pid=1160067)[0m |=============================================================================================|
[36m(EnvWorker pid=1160067)[0m | OS: 22.04.5 LTS (Jammy Jellyfish) ubuntu, Version: 22.04.5, Kernel: 5.15.0-144-generic
[36m(EnvWorker pid=1160067)[0m | Processor: Intel(R) Xeon(R) Platinum 8352V CPU @ 2.10GHz
[36m(EnvWorker pid=1160067)[0m | Cores: 72 | Logical Cores: 144
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
[36m(EnvWorker pid=1160067)[0m | Total Memory (MB): 515438 | Free Memory: 415010
[36m(EnvWorker pid=1160067)[0m | Total Page/Swap (MB): 0 | Free Page/Swap: 0
[36m(EnvWorker pid=1160067)[0m |---------------------------------------------------------------------------------------------|
......
[36m(EnvWorker pid=1160067)[0m 2025-11-13 08:18:32 [425,550ms] [Warning] [omni.physx.plugin] PhysicsUSD: CreateJoint - found a joint with disjointed body transforms, the simulation will most likely snap objects together: /World/scene_1/track_light_ltnnrc_0/base_link/meta__base_link_lights_3_0_joint
[36m(EnvWorker pid=1160067)[0m 2025-11-13 08:18:32 [425,550ms] [Warning] [omni.physx.plugin] PhysicsUSD: CreateJoint - found a joint with disjointed body transforms, the simulation will most likely snap objects together: /World/scene_1/track_light_ltnnrc_1/base_link/meta__base_link_lights_0_0_joint
[36m(EnvWorker pid=1160067)[0m 2025-11-13 08:18:32 [425,550ms] [Warning] [omni.physx.plugin] PhysicsUSD: CreateJoint - found a joint with disjointed body transforms, the simulation will most likely snap objects together: /World/scene_1/track_light_ltnnrc_1/base_link/meta__base_link_lights_1_0_joint
[36m(EnvWorker pid=1160067)[0m 2025-11-13 08:18:32 [425,550ms] [Warning] [omni.physx.plugin] PhysicsUSD: CreateJoint - found a joint with disjointed body transforms, the simulation will most likely snap objects together: /World/scene_1/track_light_ltnnrc_1/base_link/meta__base_link_lights_2_0_joint
[36m(EnvWorker pid=1160067)[0m 2025-11-13 08:18:32 [425,550ms] [Warning] [omni.physx.plugin] PhysicsUSD: CreateJoint - found a joint with disjointed body transforms, the simulation will most likely snap objects together: /World/scene_1/track_light_ltnnrc_1/base_link/meta__base_link_lights_3_0_joint
[36m(EnvWorker pid=1160067)[0m 2025-11-13 08:18:32 [425,550ms] [Warning] [omni.physx.plugin] PhysicsUSD: CreateJoint - found a joint with disjointed body transforms, the simulation will most likely snap objects together: /World/scene_1/wall_mounted_tv_dxyfxf_0/base_link/meta__base_link_togglebutton_0_0_joint

Global Step:   0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | 0/1000 [00:00<?, ?it/s]Exception occurred while running EmbodiedFSDPActor's function sync_model_to_rollout: exception is [36mray::EmbodiedFSDPActor.sync_model_to_rollout()[39m (pid=1160063, ip=10.10.221.38, actor_id=3df970c31686394c97783f9f01000000, repr=<rlinf.workers.actor.fsdp_actor_worker.EmbodiedFSDPActor object at 0x7f14361d43d0>)
  File "/data/anaconda3/envs/behavior/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/data/anaconda3/envs/behavior/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/data/em_ws/RLinf_ws/RLinf/rlinf/scheduler/worker/worker.py", line 70, in sync_func
    return func(*args, **kwargs)
  File "/data/em_ws/RLinf_ws/RLinf/rlinf/workers/actor/fsdp_actor_worker.py", line 572, in sync_model_to_rollout
    self.load_param_and_grad(self.device)
  File "/data/em_ws/RLinf_ws/RLinf/rlinf/hybrid_engines/fsdp/fsdp_model_manager.py", line 312, in load_param_and_grad
    self._strategy.onload_param_and_grad(self.model, device_id, load_grad)
  File "/data/em_ws/RLinf_ws/RLinf/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data/em_ws/RLinf_ws/RLinf/rlinf/hybrid_engines/fsdp/strategy/fsdp1.py", line 275, in onload_param_and_grad
    param.data = param.data.to(device, non_blocking=True)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 388.00 MiB. GPU 0 has a total capacity of 23.64 GiB of which 562.06 MiB is free. Process 1140273 has 384.00 MiB memory in use. Including non-PyTorch memory, this process has 22.14 GiB memory in use. Process 1209389 has 516.00 MiB memory in use. Of the allocated memory 21.35 GiB is allocated by PyTorch, and 236.09 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Exception occurred while running MultiStepRolloutWorker's function sync_model_from_actor: exception is The actor died unexpectedly before finishing this task.
	class_name: MultiStepRolloutWorker
	actor_id: 852b2daf41cea25ab3f82ea501000000
	pid: 1160065
	name: RolloutGroup:0
	namespace: RLinf
	ip: 10.10.221.38
The actor is dead because it was killed by `ray.kill`.
Exiting main process due to a failure upon worker execution.

Global Step:   0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | 0/1000 [00:04<?, ?it/s]

```

### Environment

python -V:
uv pip list:
nvidia-smi:
RLinf version:
Docker image tag: 


### Other reproduction info

_No response_

### Before submitting a new issue...

- [x] Have you checked relevant issues, FAQs (https://rlinf.readthedocs.io/en/latest/rst_source/faq.html), or asked the chatbot at the top right corner of the [documentation page](https://rlinf.readthedocs.io).

**Comment by zoeyuchao** [comment]
@JiayinDeng Hi, have u tried maniskill+openvla-oft+ppo,let us first use an easier one to test your installation.

**Comment by XuS1994** [comment]
`num_group_envs` need equal to `env GPU numbers` (1 in your yaml file), because behavior ENV is not support VectorEnv yet

**Comment by JiayinDeng** [comment]
> [@JiayinDeng](https://github.com/JiayinDeng) Hi, have u tried maniskill+openvla-oft+ppo,let us first use an easier one to test your installation.

Thank you for your advice. We have successfully run the evaluation code using:
```bash
bash examples/embodiment/eval_embodiment.sh behavior_eval
```
with the pretrained model from `https://huggingface.co/RLinf/RLinf-OpenVLAOFT-Behavior`. Therefore, we think the environment installation is correct. However, we will also try maniskill+openvla-oft+ppo to further verify this.

**Comment by JiayinDeng** [comment]
> `num_group_envs` need equal to `env GPU numbers` (1 in your yaml file), because behavior ENV is not support VectorEnv yet

Thank you. We’ve tried setting `num_group_envs` to 1, but the same issue persists. We noticed that the memory usage on the actor’s GPU spikes to nearly 100%, and within a second, the OOM error occurs. Therefore, we suspect this might be caused by an issue with the actor worker. Am I right?

**Comment by JiayinDeng** [comment]
I have solved this problem and made it run on three 4090 GPUs. The main modifications are as follows:

1. I changed the FSDP strategy to "fsdp2". The configuration file may look like:
```txt
fsdp_config:          
    strategy: "fsdp2"            # FSDP strategy: ["fsdp", "fsdp2"]
```

2. I modified the offload strategy for parameter transmission. The change is in line 177 of the file `fsdp2.py`:
```python
# return get_fsdp2_full_state_dict_all_ranks(model, False)
return get_fsdp2_full_state_dict_all_ranks(model, True)
```

By the way, I also identified a potential bug in the FSDP1 strategy. The `offload_param_and_grad` function in `fsdp1.py` seems to be ineffective, as GPU memory is not offloaded to CPU memory.
