### ISSUE TITLE
[Troubleshoot]: Error in Multi-Node Multi-GPU Setup: TypeError in MultiChannelProcessGroup._split_process_group

### ISSUE THREAD

**Issue by yuani114** [RLinf/RLinf#289]
### Problem description

I'm trying to run the script examples/coding_online_rl/run_main_coding_online_rl.sh from this project. It works just fine on a single node with 8 GPUs, but when I scale it up to a multi-node setup (2 nodes, each with 4 GPUs), I run into this error during model synchronization:


```
Exception occurred while running MegatronActor's function sync_model_to_rollout: exception is [36mray::MegatronActor.sync_model_to_rollout()[39m (pid=959, ip=10.100.162.94, actor_id=1f82b5d710af3837fb4a602d03000000, repr=<rlinf.workers.actor.megatron_actor_worker.MegatronActor object at 0x7f2744b5bf90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/worker/worker.py", line 70, in sync_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/workers/actor/megatron_actor_worker.py", line 1254, in sync_model_to_rollout
    self.send(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/worker/worker.py", line 70, in sync_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/worker/worker.py", line 517, in send
    return group.send(object=object, async_op=async_op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 214, in send
    send_work(None)
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/async_work.py", line 88, in __call__
    self._result = self._func(*self._args, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 229, in _atomic_send
    self._init_p2p_process_group()
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 513, in _init_p2p_process_group
    self._mc_group.init(
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/multi_channel_pg.py", line 162, in init
    MultiChannelProcessGroup._split_process_group(
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/multi_channel_pg.py", line 475, in _split_process_group
    pg, _ = MultiChannelProcessGroup._new_process_group_helper(
    ^^^^^
TypeError: cannot unpack non-iterable NoneType object
```


Any suggestions on how to debug or fix? Thanks!

### Configuration YAML file

```
defaults:
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

cluster:
  num_nodes: 2
  component_placement:
    # online rl must use disaggregated placement.
    rollout: 0-1
    inference: 4-7
    actor: 2-3
    reward: 4-7

runner:
  task_type: coding_online_rl
  logger:
    log_path: ${runner.output_dir}/${runner.experiment_name}
    project_name: rlinf
    experiment_name: ${runner.experiment_name}
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 10
  max_steps: -1

  val_check_interval: 1
  save_interval: 10

  seq_length: 8192

  enable_dynamic_batch_size: False
  max_tokens_per_mbs: 8192

  resume_dir: null
  experiment_name: online-ppo-1.5b-pipeline
  output_dir: /code/ruanwei/RLinf-online/RLinf/examples/coding_online_rl/logs

algorithm:
  # online rl use ppo.
  group_size: 1

  n_minibatches: 2
  training_batch_size_per_gpu: 1 # micro batch size
  rollout_batch_size_per_gpu: null # If set to null, rollout_batch_size will be evenly divided across all inference instances. You can reduce this parameter if inference consumes too much GPU memory.

  # mbs to do log prob inference, can be set to
  # lower than rollout_batch_size_per_gpu to reduce
  # memory usage
  logprob_forward_micro_batch_size: 1 # ${.rollout_batch_size_per_gpu}

  # val rollout mbs
  val_rollout_batch_size_per_gpu: 4 # ${.rollout_batch_size_per_gpu}

  recompute_logprobs: True
  shuffle_rollout: False

  max_num_gen_batches: 1

  # PPO loss params (no critic model)
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0 # 0.001
  kl_penalty_type: low_var_kl
  ratio_clip_eps: 0.2
  entropy_bonus: 0.0
  calculate_entropy: False
  clip_ratio_c: null # 3.0

  # Control critic usage (similar to AReaL's disable_head)
  use_critic: False  # Disable critic model
  use_value_loss: False  # Disable value loss computation
  
  # PPO parameters for no-critic setup
  gamma: 0.99
  gae_lambda: 0.95
  # value_clip and huber_delta not needed without critic

  # Use no-critic GAE advantage computation
  adv_type: gae
  normalize_advantages: False
  early_stop_imp_ratio: 5.0
  use_valid_token_scale: False

  # params for rollout
  sampling_params:
    use_greedy: False
    temperature: 0.1
    top_k: 1000000
    top_p: 1.0
    repetition_penalty: 1.0
    max_new_tokens: ${subtract:${runner.seq_length}, ${data.max_prompt_length}}
    min_new_tokens: 1
    stop: [
      "<|endoftext|>",
      "<|fim_prefix|>",
      "<|fim_middle|>",
      "<|fim_suffix|>",
      "<|fim_pad|>",
      "<|repo_name|>",
      "<|file_sep|>",
      "<|im_start|>",
      "<|im_end|>",
    ]

inference:
  model_arch: ${rollout.model_arch}
  group_name: "InferenceGroup"
  load_from_actor: True
  model:
    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 1
    sequence_parallel: True

rollout:
  group_name: "RolloutGroup"

  gpu_memory_utilization: 0.55

  model_dir: /models/Qwen/Qwen2.5-Coder-1.5B
  model_arch: qwen2.5
  precision: ${actor.model.precision} # precision for rollout model, support [fp16, bf16, fp32]  
  enforce_eager: False         # if False, rollout engine will capture cuda graph, which will take more time to initialize.
  distributed_executor_backend: mp   # ray or mp
  disable_log_stats: False
  detokenize: True            # Whether to detokenize the output.
  padding: null               # will be tokenizer.pad_token_id if null. it is used to filter megatron's padding for rollout engine
  eos: null                   # will be tokenizer.eos_token_id if null.

  rollout_backend: sglang     # online_rl now only support sglang 

  sglang:
    attention_backend: triton # [flashinfer, triton] for more, see sglang's doc
    decode_log_interval: 500000 # the interval for SGLang to log the decode time and other stats.
    use_torch_compile: False # enable torch_compile in SGLang for rollout.
    torch_compile_max_bs: 128 # the maximum batch size for torch compile. If the batch size is larger than this, torch compile will not be used.

  vllm:
    # not used, but reserved to pass config validate
    attention_backend: FLASH_ATTN #[FLASH_ATTN,XFORMERS] for more, see vllm's doc
    enable_chunked_prefill: True  # enable vllm to use chunked_prefill.
    enable_prefix_caching: True   # enable vllm to use prefix_caching.
    enable_flash_infer_sampler: True # if True, vllm will use flashinfer to do sampling.

  return_logprobs: ${not:${algorithm.recompute_logprobs}}

  tensor_parallel_size: 1
  pipeline_parallel_size: 1

  validate_weight: False # whether to send all weights at first for weight comparison.
  validate_save_dir: null # the directory to save the weights for comparison. If validate_weight is True, this will be used to save the weights for comparison.
  print_outputs: False         # whether to print the outputs (token ids, texts, etc.) of rollout engine.

  max_running_requests: 64 # the maximum number of running requests in the rollout engine.
  cuda_graph_max_bs: 128 # the maximum batch size for cuda graph. If the batch size is larger than this, cuda graph will not be used.

data:
  # not used, but reserved to pass config validate
  max_prompt_length: 1024
  rollout_batch_size: 16
  seed: 1234

actor:
  group_name: "ActorGroup"
  training_backend: megatron
  mcore_gpt: True
  spec_name: decoder_gpt

  checkpoint_load_path: null

  offload_optimizer: True
  offload_weight: True
  offload_grad: True

  enable_dp_load_balance: False

  calculate_flops: False

  seed: 1234

  model:
    precision: bf16
    add_bias_linear: False

    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 1

    activation: swiglu
    sequence_parallel: True
    # recompute_method: block
    # recompute_granularity: selective

    recompute_method: block
    recompute_granularity: full
    recompute_num_layers: 20

    seq_length: ${runner.seq_length}
    encoder_seq_length: ${runner.seq_length}

    normalization: rmsnorm

    position_embedding_type: rope

    apply_rope_fusion: True
    bias_dropout_fusion: False
    persist_layer_norm: False
    bias_activation_fusion: False
    attention_softmax_in_fp32: True
    batch_p2p_comm: False
    variable_seq_lengths: True
    gradient_accumulation_fusion: False
    moe_token_dispatcher_type: alltoall
    use_cpu_initialization: False

  optim:
    optimizer: adam
    bf16: True
    fp16: False
    lr: 2e-06
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    min_lr: 2.0e-7
    weight_decay: 0.05
    use_distributed_optimizer: True
    overlap_grad_reduce: False
    overlap_param_gather: False
    optimizer_enable_pin: False
    overlap_param_gather_with_optimizer_step: False
    clip_grad: 0.8
    loss_scale: 65536

  lr_sched:
    lr_warmup_fraction: 0.01
    lr_warmup_init: 0.0
    lr_warmup_iters: 0
    max_lr: 2.0e-6
    min_lr: 0.0
    lr_decay_style: constant
    lr_decay_iters: 10

  tokenizer:
    tokenizer_model: ${rollout.model_dir}
    use_fast: False
    trust_remote_code: True
    padding_side: 'right'

  megatron:
    ddp_bucket_size: null
    distributed_backend: nccl # Support 'nccl' and 'gloo'
    distributed_timeout_minutes: 30
    ckpt_format: torch
    use_dist_ckpt: False
    tp_comm_bootstrap_backend: nccl
    tp_comm_overlap_cfg: null # tp_comm_overlap_cfg.yaml
    use_hf_ckpt: True # if true, will transfer hf model to generate megatron checkpoint and use it for training.
    use_profiler: False # if true, will enable torch profiler when training, pay attention it has influence on performance

    ckpt_convertor: # config for ckpt convertor
      model: Qwen2.5-Coder-1.5B
      model_type: null # will be set by hf model's config if null
      hf_model_path: ${rollout.model_dir} # path to the hf model
      save_path: ${runner.output_dir}/${runner.experiment_name}/converted_ckpts/actor
      use_gpu_num : 0
      use_gpu_index: null
      process_num: 16 # number of processes to use for checkpointing
      tensor_model_parallel_size: ${actor.model.tensor_model_parallel_size}
      pipeline_model_parallel_size: ${actor.model.pipeline_model_parallel_size}

    profiler: # profile megatron when inference and traning
      output_dir: ${runner.output_dir}/${runner.experiment_name}/profiler
      activities: ["cpu", "cuda"]
      record_shapes: False
      profile_memory: False
      with_stack: False
      with_flops: False
      with_modules: True
      export_tensorboard: True
      export_chrome_trace: False
      chrome_filename_prefix: "chrome_trace"
      schedule_warmup: 2
      schedule_active: 1
      schedule_repeat: 1 # inference and training will repeat such times
      # schedule_wait: it will be set at runtime

reward:
  # online rl get reward from user judge.
  use_reward_model: False

critic:
  use_critic_model: False

server:
  # online serving and user reward tracking.
  online_router:
    host: 0.0.0.0
    port: 8081

  tracking_rollout:
    host: 0.0.0.0
    port: 8082


```

### Log file

```
[INFO 20:26:24 RLinf] RLinf is running on a cluster with 2 nodes and 8 accelerators. The nodes' details are: [NodeInfo(node_rank=0, ray_id='e535e49e1cdf67db61267397dfc4bd4697b9399c3841ea107a46fd67', node_ip='10.100.162.94', accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, num_accelerators=4, num_cpus=80), NodeInfo(node_rank=0, ray_id='b346e3ef5b5ae9038b7ae949b8118bc7dbf0be34878640087640b34a', node_ip='10.100.241.32', accelerator_type=<AcceleratorType.NV_GPU: 'NV_GPU'>, num_accelerators=4, num_cpus=80)]
['0-1']
['4-7']
['2-3']
['4-7']
```
...


```
[36m(MegatronInference pid=930, ip=10.100.241.32)[0m INFO:megatron.core.optimizer:Setting up optimizer with config OptimizerConfig(optimizer='adam', lr=2e-06, min_lr=0.0, decoupled_lr=None, decoupled_min_lr=None, weight_decay=0.05, fp8_recipe=None, fp16=False, bf16=True, reuse_grad_buf_for_mxfp8_param_ag=False, params_dtype=torch.bfloat16, use_precision_aware_optimizer=False, store_param_remainders=True, main_grads_dtype=torch.float32, main_params_dtype=torch.float32, exp_avg_dtype=torch.float32, exp_avg_sq_dtype=torch.float32, loss_scale=65536, initial_loss_scale=4294967296, min_loss_scale=1.0, loss_scale_window=1000, hysteresis=2, adam_beta1=0.9, adam_beta2=0.95, adam_eps=1e-05, sgd_momentum=0.9, use_distributed_optimizer=True, overlap_param_gather_with_optimizer_step=False, optimizer_cpu_offload=False, optimizer_offload_fraction=0.0, use_torch_optimizer_for_cpu_offload=False, overlap_cpu_optimizer_d2h_h2d=False, pin_cpu_grads=True, pin_cpu_params=True, clip_grad=0.8, log_num_zeros_in_grad=False, barrier_with_L1_time=False, timers=<megatron.core.timers.Timers object at 0x7f119555f450>, config_logger_dir='')
[36m(MegatronInference pid=930, ip=10.100.241.32)[0m INFO:megatron.core.optimizer_param_scheduler:> learning rate decay style: constant
[36m(MegatronInference pid=930, ip=10.100.241.32)[0m could not find arguments in the checkpoint ...
[36m(MegatronInference pid=930, ip=10.100.241.32)[0m  checkpoint version 3.0
[36m(MegatronInference pid=930, ip=10.100.241.32)[0m   successfully loaded checkpoint from /code/ruanwei/RLinf-online/RLinf/examples/coding_online_rl/logs/online-ppo-1.5b-pipeline/converted_ckpts/actor [ t 1/2, p 1/1 ] at iteration 0

Global Step:   0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | 0/10 [00:00<?, ?it/s][36m(MegatronInference pid=936, ip=10.100.241.32)[0m (min, max) time across ranks (ms):
[36m(MegatronInference pid=936, ip=10.100.241.32)[0m     load-checkpoint ................................: (3254.93, 3254.98)
[36m(OnlineRouterWorker pid=933, ip=10.100.162.94)[0m [INFO 20:30:54 OnlineRouterWorker-Rank-0][online_router_worker.py:112] service started on 0.0.0.0:8081
[36m(OnlineRouterWorker pid=933, ip=10.100.162.94)[0m [INFO 20:30:54 OnlineRouterWorker-Rank-0][online_router_worker.py:227] Starting model synchronization...
[36m(OnlineRouterWorker pid=933, ip=10.100.162.94)[0m [INFO 20:30:54 OnlineRouterWorker-Rank-0][online_router_worker.py:245] All old requests completed, sync can proceed
[36m(OnlineRouterWorker pid=933, ip=10.100.162.94)[0m INFO:     Started server process [933]
[36m(OnlineRouterWorker pid=933, ip=10.100.162.94)[0m INFO:     Waiting for application startup.
[36m(OnlineRouterWorker pid=933, ip=10.100.162.94)[0m INFO:     Application startup complete.
[36m(OnlineRouterWorker pid=933, ip=10.100.162.94)[0m INFO:     Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)
[36m(ServerRolloutWorker pid=934, ip=10.100.162.94)[0m [INFO 20:30:54 ServerRolloutWorker-Rank-0][server_rollout_worker.py:218] service started on 0.0.0.0:8082
[36m(ServerRolloutWorker pid=934, ip=10.100.162.94)[0m INFO:     Started server process [934]
[36m(ServerRolloutWorker pid=934, ip=10.100.162.94)[0m INFO:     Waiting for application startup.
[36m(ServerRolloutWorker pid=934, ip=10.100.162.94)[0m INFO:     Application startup complete.
[36m(ServerRolloutWorker pid=934, ip=10.100.162.94)[0m INFO:     Uvicorn running on http://0.0.0.0:8082 (Press CTRL+C to quit)
[36m(MegatronActor pid=958, ip=10.100.162.94)[0m [DEBUG 20:30:54 ActorGroup-Rank-0][collective_group.py:452] Collective group cg-ActorGroup:0-RolloutGroup:0:0 created with workers: ['ActorGroup:0', 'RolloutGroup:0:0']
[36m(MegatronActor pid=959, ip=10.100.162.94)[0m [DEBUG 20:30:54 ActorGroup-Rank-1][collective_group.py:452] Collective group cg-ActorGroup:1-RolloutGroup:1:0 created with workers: ['ActorGroup:1', 'RolloutGroup:1:0']
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m [DEBUG 20:30:54 RolloutGroup:0-Rank-0][collective_group.py:458] Collective group cg-ActorGroup:0-RolloutGroup:0:0 found with workers: ['ActorGroup:0', 'RolloutGroup:0:0']
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m [DEBUG 20:30:54 RolloutGroup:1-Rank-0][collective_group.py:458] Collective group cg-ActorGroup:1-RolloutGroup:1:0 found with workers: ['ActorGroup:1', 'RolloutGroup:1:0']
Exception occurred while running MegatronActor's function sync_model_to_rollout: exception is [36mray::MegatronActor.sync_model_to_rollout()[39m (pid=959, ip=10.100.162.94, actor_id=1f82b5d710af3837fb4a602d03000000, repr=<rlinf.workers.actor.megatron_actor_worker.MegatronActor object at 0x7f2744b5bf90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/worker/worker.py", line 70, in sync_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/workers/actor/megatron_actor_worker.py", line 1254, in sync_model_to_rollout
    self.send(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/worker/worker.py", line 70, in sync_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/worker/worker.py", line 517, in send
    return group.send(object=object, async_op=async_op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 214, in send
    send_work(None)
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/async_work.py", line 88, in __call__
    self._result = self._func(*self._args, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 229, in _atomic_send
    self._init_p2p_process_group()
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 513, in _init_p2p_process_group
    self._mc_group.init(
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/multi_channel_pg.py", line 162, in init
    MultiChannelProcessGroup._split_process_group(
  File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/multi_channel_pg.py", line 475, in _split_process_group
    pg, _ = MultiChannelProcessGroup._new_process_group_helper(
    ^^^^^
TypeError: cannot unpack non-iterable NoneType object
Exception occurred while running SGLangWorker's function sync_model_from_actor: exception is The actor died unexpectedly before finishing this task.
	class_name: SGLangWorker
	actor_id: 15a0ae6ded37918d3facb5f703000000
	pid: 936
	name: RolloutGroup:1
	namespace: RLinf
	ip: 10.100.162.94
The actor is dead because it was killed by `ray.kill`.
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m [DEBUG 20:30:54 RolloutGroup:0-Rank-0][collective_group.py:509] Initializing process group for collective group cg-ActorGroup:0-RolloutGroup:0:0, master address 10.100.162.94, master port 55439, world size 2, rank 1
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m [DEBUG 20:30:54 RolloutGroup:0-Rank-0][multi_channel_pg.py:118] Setting timeout to 180 minutes for group cg-ActorGroup:0-RolloutGroup:0:0
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m [DEBUG 20:30:54 RolloutGroup:0-Rank-0][multi_channel_pg.py:129] init cg-ActorGroup:0-RolloutGroup:0:0
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m [DEBUG 20:30:54 RolloutGroup:0-Rank-0][multi_channel_pg.py:146] cg-ActorGroup:0-RolloutGroup:0:0 init sucess, start split
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m [2025-11-17 20:30:54] Scheduler hit an exception: Traceback (most recent call last):
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/opt/conda/lib/python3.11/site-packages/sglang/srt/managers/scheduler.py", line 2311, in run_scheduler_process
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     scheduler.event_loop_overlap()
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     return func(*args, **kwargs)
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m            ^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/opt/conda/lib/python3.11/site-packages/sglang/srt/managers/scheduler.py", line 662, in event_loop_overlap
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     self.process_input_requests(recv_reqs)
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/opt/conda/lib/python3.11/site-packages/sglang/srt/managers/scheduler.py", line 889, in process_input_requests
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     output = self._request_dispatcher(recv_req)
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/opt/conda/lib/python3.11/site-packages/sglang/utils.py", line 471, in __call__
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     return fn(obj)
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m            ^^^^^^^
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/hybrid_engines/sglang/common/sgl_scheduler.py", line 95, in sync_hf_weight
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     state_dict = self._rlinf_worker.recv(
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/worker/worker.py", line 70, in sync_func
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     return func(*args, **kwargs)
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m            ^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/worker/worker.py", line 544, in recv
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     return group.recv(async_op=async_op)
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 273, in recv
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     recv_work(None)
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/async_work.py", line 88, in __call__
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     self._result = self._func(*self._args, **self._kwargs)
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 282, in _atomic_recv
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     self._init_p2p_process_group()
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 513, in _init_p2p_process_group
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     self._mc_group.init(
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/multi_channel_pg.py", line 162, in init
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     MultiChannelProcessGroup._split_process_group(
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/multi_channel_pg.py", line 475, in _split_process_group
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     pg, _ = MultiChannelProcessGroup._new_process_group_helper(
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m     ^^^^^
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m TypeError: cannot unpack non-iterable NoneType object
[36m(SGLangWorker pid=935, ip=10.100.162.94)[0m 
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m [DEBUG 20:30:54 RolloutGroup:1-Rank-0][collective_group.py:509] Initializing process group for collective group cg-ActorGroup:1-RolloutGroup:1:0, master address 10.100.162.94, master port 55085, world size 2, rank 1
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m [DEBUG 20:30:54 RolloutGroup:1-Rank-0][multi_channel_pg.py:118] Setting timeout to 180 minutes for group cg-ActorGroup:1-RolloutGroup:1:0
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m [DEBUG 20:30:54 RolloutGroup:1-Rank-0][multi_channel_pg.py:129] init cg-ActorGroup:1-RolloutGroup:1:0
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m [DEBUG 20:30:54 RolloutGroup:1-Rank-0][multi_channel_pg.py:146] cg-ActorGroup:1-RolloutGroup:1:0 init sucess, start split
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m [2025-11-17 20:30:54] Scheduler hit an exception: Traceback (most recent call last):
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/opt/conda/lib/python3.11/site-packages/sglang/srt/managers/scheduler.py", line 2311, in run_scheduler_process
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     scheduler.event_loop_overlap()
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     return func(*args, **kwargs)
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m            ^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/opt/conda/lib/python3.11/site-packages/sglang/srt/managers/scheduler.py", line 662, in event_loop_overlap
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     self.process_input_requests(recv_reqs)
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/opt/conda/lib/python3.11/site-packages/sglang/srt/managers/scheduler.py", line 889, in process_input_requests
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     output = self._request_dispatcher(recv_req)
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/opt/conda/lib/python3.11/site-packages/sglang/utils.py", line 471, in __call__
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     return fn(obj)
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m            ^^^^^^^
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/hybrid_engines/sglang/common/sgl_scheduler.py", line 95, in sync_hf_weight
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     state_dict = self._rlinf_worker.recv(
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/worker/worker.py", line 70, in sync_func
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     return func(*args, **kwargs)
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m            ^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/worker/worker.py", line 544, in recv
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     return group.recv(async_op=async_op)
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 273, in recv
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     recv_work(None)
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/async_work.py", line 88, in __call__
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     self._result = self._func(*self._args, **self._kwargs)
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 282, in _atomic_recv
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     self._init_p2p_process_group()
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/collective_group.py", line 513, in _init_p2p_process_group
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     self._mc_group.init(
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/multi_channel_pg.py", line 162, in init
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     MultiChannelProcessGroup._split_process_group(
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m   File "/code/ruanwei/RLinf-online/RLinf/rlinf/scheduler/collective/multi_channel_pg.py", line 475, in _split_process_group
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     pg, _ = MultiChannelProcessGroup._new_process_group_helper(
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m     ^^^^^
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m TypeError: cannot unpack non-iterable NoneType object
[36m(SGLangWorker pid=936, ip=10.100.162.94)[0m 
[36m(MegatronActor pid=958, ip=10.100.162.94)[0m [DEBUG 20:30:54 ActorGroup-Rank-0][collective_group.py:509] Initializing process group for collective group cg-ActorGroup:0-RolloutGroup:0:0, master address 10.100.162.94, master port 55439, world size 2, rank 0
[36m(MegatronActor pid=958, ip=10.100.162.94)[0m [DEBUG 20:30:54 ActorGroup-Rank-0][multi_channel_pg.py:118] Setting timeout to 180 minutes for group cg-ActorGroup:0-RolloutGroup:0:0
[36m(MegatronActor pid=958, ip=10.100.162.94)[0m [DEBUG 20:30:54 ActorGroup-Rank-0][multi_channel_pg.py:129] init cg-ActorGroup:0-RolloutGroup:0:0
[36m(MegatronActor pid=958, ip=10.100.162.94)[0m [DEBUG 20:30:54 ActorGroup-Rank-0][multi_channel_pg.py:146] cg-ActorGroup:0-RolloutGroup:0:0 init sucess, start split
[36m(MegatronActor pid=959, ip=10.100.162.94)[0m [DEBUG 20:30:54 ActorGroup-Rank-1][collective_group.py:509] Initializing process group for collective group cg-ActorGroup:1-RolloutGroup:1:0, master address 10.100.162.94, master port 55085, world size 2, rank 0
[36m(MegatronActor pid=959, ip=10.100.162.94)[0m [DEBUG 20:30:54 ActorGroup-Rank-1][multi_channel_pg.py:118] Setting timeout to 180 minutes for group cg-ActorGroup:1-RolloutGroup:1:0
[36m(MegatronActor pid=959, ip=10.100.162.94)[0m [DEBUG 20:30:54 ActorGroup-Rank-1][multi_channel_pg.py:129] init cg-ActorGroup:1-RolloutGroup:1:0
[36m(MegatronActor pid=959, ip=10.100.162.94)[0m [DEBUG 20:30:54 ActorGroup-Rank-1][multi_channel_pg.py:146] cg-ActorGroup:1-RolloutGroup:1:0 init sucess, start split
[33m(raylet)[0m A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff9e088630082be9bdc210a67c03000000 Worker ID: 676eb081eb17630f8a1d466f1db3a7df2b25a1d452f8f925fcbd28ea Node ID: e535e49e1cdf67db61267397dfc4bd4697b9399c3841ea107a46fd67 Worker IP address: 10.100.162.94 Worker port: 10012 Worker PID: 935 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
[33m(raylet)[0m A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff15a0ae6ded37918d3facb5f703000000 Worker ID: b4fbf15b554ff6b85263fe181e34961c3dd299665dc88c1cc7f9df6a Node ID: e535e49e1cdf67db61267397dfc4bd4697b9399c3841ea107a46fd67 Worker IP address: 10.100.162.94 Worker port: 10013 Worker PID: 936 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Exiting main process due to a failure upon worker execution.

Global Step:   0%|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | 0/10 [00:01<?, ?it/s]
```

### Environment

python -V:
uv pip list:
nvidia-smi:
RLinf version:
Docker image tag: 


### Other reproduction info

_No response_

### Before submitting a new issue...

- [x] Have you checked relevant issues, FAQs (https://rlinf.readthedocs.io/en/latest/rst_source/faq.html), or asked the chatbot at the top right corner of the [documentation page](https://rlinf.readthedocs.io).

**Comment by qurakchin** [comment]
I can't reproduce this bug. I have tried the docker image "rlinf/rlinf:math-rlinf0.1-torch2.5.1-sglang0.4.4-vllm0.7.1-megatron0.11.0-te2.1" and 2 images more, and tested 1 node 8 gpus and 2 nodes 8gpus with 2 placement policy(
rollout: 0-3, nference: 4-5, actor: 6-7, reward: 0-3; rollout: 0-1, inference: 4-7, actor: 2-3, reward: 4-7). please list your RLinf version and docker image tag to help me to reproduce this

**Comment by yuani114** [comment]
> I can't reproduce this bug. I have tried the docker image "rlinf/rlinf:math-rlinf0.1-torch2.5.1-sglang0.4.4-vllm0.7.1-megatron0.11.0-te2.1" and 2 images more, and tested 1 node 8 gpus and 2 nodes 8gpus with 2 placement policy( rollout: 0-3, nference: 4-5, actor: 6-7, reward: 0-3; rollout: 0-1, inference: 4-7, actor: 2-3, reward: 4-7). please list your RLinf version and docker image tag to help me to reproduce this

I just re-cloned the project and found that the bug has disappeared. It turns out the issue was likely caused by some unintended code modifications I made earlier. Sorry for the trouble this has caused you!
