### ISSUE TITLE
[Troubleshoot]:Checkpoint converter fails: mp_rank_01/model_optim_rng.pt not found

### ISSUE THREAD

**Issue by yuani114** [RLinf/RLinf#322]
### Problem description

I'm using the official example training script 
`examples/coding_online_rl/run_main_coding_online_rl.sh`
After training, I noticed the saved checkpoint has an unexpected structure where only mp_rank_00 contains model_optim_rng.pt while mp_rank_01 only has distrib_optim.pt. 

<img width="553" height="177" alt="Image" src="https://github.com/user-attachments/assets/6ea50183-9615-4d66-94ce-10e5407d2fac" />

When I tried to convert this checkpoint to HuggingFace format using `toolkits/ckpt_convertor/mg2hf_1.5b.sh`, the script failed with `AssertionError: pt_file not exist! .../mp_rank_01/model_optim_rng.pt.` Looking at the code in utils/mg_loader.py,
```
for tp_rank in range(Operation.global_tp):
    if Operation.global_pp == 1:
        filename = f"{pt_path}/mp_rank_{tp_rank:02d}/model_optim_rng.pt"  # Expects file in all ranks
```
 it expects model_optim_rng.pt to exist in all rank directories, but the training script only saved it in mp_rank_00.  Is this saved checkpoint structure expected? How should this be fixed? Thanks for your help!

### Configuration YAML file

```
defaults:
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

storage:
  storage_dir: /code/ruanwei/RLinf-online/RLinf/training_data_new

cluster:
  num_nodes: 1
  component_placement:
    # online rl must use disaggregated placement.
    rollout: 4-7
    inference: 2-3
    actor: 0-1
    reward: 4-7
runner:
  task_type: coding_online_rl
  logger:
    log_path: ${runner.output_dir}/${runner.experiment_name}
    project_name: rlinf
    experiment_name: ${runner.experiment_name}
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 10
  max_steps: -1

  val_check_interval: 1
  save_interval: 5

  seq_length: 8192

  enable_dynamic_batch_size: False
  max_tokens_per_mbs: 8192

  resume_dir: null
  experiment_name: online-ppo-1.5b-pipeline
  output_dir: /code/ruanwei/RLinf-online/RLinf/examples/coding_online_rl/logs

algorithm:
  # online rl use ppo.
  group_size: 1

  n_minibatches: 2
  training_batch_size_per_gpu: 1 # micro batch size
  rollout_batch_size_per_gpu: null # If set to null, rollout_batch_size will be evenly divided across all inference instances. You can reduce this parameter if inference consumes too much GPU memory.

  # mbs to do log prob inference, can be set to
  # lower than rollout_batch_size_per_gpu to reduce
  # memory usage
  logprob_forward_micro_batch_size: 1 # ${.rollout_batch_size_per_gpu}

  # val rollout mbs
  val_rollout_batch_size_per_gpu: 4 # ${.rollout_batch_size_per_gpu}

  recompute_logprobs: True
  shuffle_rollout: False

  max_num_gen_batches: 1

  # PPO loss params (no critic model)
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0 # 0.001
  kl_penalty_type: low_var_kl
  ratio_clip_eps: 0.2
  entropy_bonus: 0.0
  calculate_entropy: False
  clip_ratio_c: null # 3.0

  # Control critic usage (similar to AReaL's disable_head)
  use_critic: False  # Disable critic model
  use_value_loss: False  # Disable value loss computation
  
  # PPO parameters for no-critic setup
  gamma: 0.99
  gae_lambda: 0.95
  # value_clip and huber_delta not needed without critic

  # Use no-critic GAE advantage computation
  adv_type: gae
  normalize_advantages: False
  early_stop_imp_ratio: 5.0
  use_valid_token_scale: False

  # params for rollout
  sampling_params:
    use_greedy: False
    temperature: 0.1
    top_k: 1000000
    top_p: 1.0
    repetition_penalty: 1.0
    max_new_tokens: ${subtract:${runner.seq_length}, ${data.max_prompt_length}}
    min_new_tokens: 1
    stop: [
      "<|endoftext|>",
      "<|fim_prefix|>",
      "<|fim_middle|>",
      "<|fim_suffix|>",
      "<|fim_pad|>",
      "<|repo_name|>",
      "<|file_sep|>",
      "<|im_start|>",
      "<|im_end|>",
    ]

inference:
  model_arch: ${rollout.model_arch}
  group_name: "InferenceGroup"
  load_from_actor: True
  model:
    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 1
    sequence_parallel: True

rollout:
  group_name: "RolloutGroup"

  gpu_memory_utilization: 0.55

  model_dir: /models/Qwen/Qwen2.5-Coder-1.5B
  model_arch: qwen2.5
  precision: ${actor.model.precision} # precision for rollout model, support [fp16, bf16, fp32]  
  enforce_eager: False         # if False, rollout engine will capture cuda graph, which will take more time to initialize.
  distributed_executor_backend: mp   # ray or mp
  disable_log_stats: False
  detokenize: True            # Whether to detokenize the output.
  padding: null               # will be tokenizer.pad_token_id if null. it is used to filter megatron's padding for rollout engine
  eos: null                   # will be tokenizer.eos_token_id if null.

  rollout_backend: sglang     # online_rl now only support sglang 

  sglang:
    attention_backend: triton # [flashinfer, triton] for more, see sglang's doc
    decode_log_interval: 500000 # the interval for SGLang to log the decode time and other stats.
    use_torch_compile: False # enable torch_compile in SGLang for rollout.
    torch_compile_max_bs: 128 # the maximum batch size for torch compile. If the batch size is larger than this, torch compile will not be used.

  vllm:
    # not used, but reserved to pass config validate
    attention_backend: FLASH_ATTN #[FLASH_ATTN,XFORMERS] for more, see vllm's doc
    enable_chunked_prefill: True  # enable vllm to use chunked_prefill.
    enable_prefix_caching: True   # enable vllm to use prefix_caching.
    enable_flash_infer_sampler: True # if True, vllm will use flashinfer to do sampling.

  return_logprobs: ${not:${algorithm.recompute_logprobs}}

  tensor_parallel_size: 1
  pipeline_parallel_size: 1

  validate_weight: False # whether to send all weights at first for weight comparison.
  validate_save_dir: null # the directory to save the weights for comparison. If validate_weight is True, this will be used to save the weights for comparison.
  print_outputs: False         # whether to print the outputs (token ids, texts, etc.) of rollout engine.

  max_running_requests: 64 # the maximum number of running requests in the rollout engine.
  cuda_graph_max_bs: 128 # the maximum batch size for cuda graph. If the batch size is larger than this, cuda graph will not be used.

data:
  # not used, but reserved to pass config validate
  max_prompt_length: 1024
  rollout_batch_size: 16
  seed: 1234

actor:
  group_name: "ActorGroup"
  training_backend: megatron
  mcore_gpt: True
  spec_name: decoder_gpt

  checkpoint_load_path: null

  offload_optimizer: True
  offload_weight: True
  offload_grad: True

  enable_dp_load_balance: False

  calculate_flops: False

  seed: 1234

  model:
    precision: bf16
    add_bias_linear: False

    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 1

    activation: swiglu
    sequence_parallel: True
    # recompute_method: block
    # recompute_granularity: selective

    recompute_method: block
    recompute_granularity: full
    recompute_num_layers: 20

    seq_length: ${runner.seq_length}
    encoder_seq_length: ${runner.seq_length}

    normalization: rmsnorm

    position_embedding_type: rope

    apply_rope_fusion: True
    bias_dropout_fusion: False
    persist_layer_norm: False
    bias_activation_fusion: False
    attention_softmax_in_fp32: True
    batch_p2p_comm: False
    variable_seq_lengths: True
    gradient_accumulation_fusion: False
    moe_token_dispatcher_type: alltoall
    use_cpu_initialization: False

  optim:
    optimizer: adam
    bf16: True
    fp16: False
    lr: 2e-06
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    min_lr: 2.0e-7
    weight_decay: 0.05
    use_distributed_optimizer: True
    overlap_grad_reduce: False
    overlap_param_gather: False
    optimizer_enable_pin: False
    overlap_param_gather_with_optimizer_step: False
    clip_grad: 0.8
    loss_scale: 65536

  lr_sched:
    lr_warmup_fraction: 0.01
    lr_warmup_init: 0.0
    lr_warmup_iters: 0
    max_lr: 2.0e-6
    min_lr: 0.0
    lr_decay_style: constant
    lr_decay_iters: 10

  tokenizer:
    tokenizer_model: ${rollout.model_dir}
    use_fast: False
    trust_remote_code: True
    padding_side: 'right'

  megatron:
    ddp_bucket_size: null
    distributed_backend: nccl # Support 'nccl' and 'gloo'
    distributed_timeout_minutes: 30
    ckpt_format: torch
    use_dist_ckpt: False
    tp_comm_bootstrap_backend: nccl
    tp_comm_overlap_cfg: null # tp_comm_overlap_cfg.yaml
    use_hf_ckpt: True # if true, will transfer hf model to generate megatron checkpoint and use it for training.
    use_profiler: False # if true, will enable torch profiler when training, pay attention it has influence on performance

    ckpt_convertor: # config for ckpt convertor
      model: Qwen2.5-Coder-1.5B
      model_type: null # will be set by hf model's config if null
      hf_model_path: ${rollout.model_dir} # path to the hf model
      save_path: ${runner.output_dir}/${runner.experiment_name}/converted_ckpts/actor
      use_gpu_num : 0
      use_gpu_index: null
      process_num: 16 # number of processes to use for checkpointing
      tensor_model_parallel_size: ${actor.model.tensor_model_parallel_size}
      pipeline_model_parallel_size: ${actor.model.pipeline_model_parallel_size}

    profiler: # profile megatron when inference and traning
      output_dir: ${runner.output_dir}/${runner.experiment_name}/profiler
      activities: ["cpu", "cuda"]
      record_shapes: False
      profile_memory: False
      with_stack: False
      with_flops: False
      with_modules: True
      export_tensorboard: True
      export_chrome_trace: False
      chrome_filename_prefix: "chrome_trace"
      schedule_warmup: 2
      schedule_active: 1
      schedule_repeat: 1 # inference and training will repeat such times
      # schedule_wait: it will be set at runtime

reward:
  # online rl get reward from user judge.
  use_reward_model: False

critic:
  use_critic_model: False

server:
  # online serving and user reward tracking.
  online_router:
    host: 0.0.0.0
    port: 8081

  tracking_rollout:
    host: 0.0.0.0
    port: 8082
```

### Log file

```
 File "/code/ruanwei/RLinf-online/RLinf/toolkits/ckpt_convertor/convert_mg_to_middle_file.py", line 845, in <module>
    main()
  File "/code/ruanwei/RLinf-online/RLinf/toolkits/ckpt_convertor/convert_mg_to_middle_file.py", line 714, in main
    args.iteration = get_megatron_iteration(args)
  File "/code/ruanwei/RLinf-online/RLinf/toolkits/ckpt_convertor/convert_mg_to_middle_file.py", line 238, in get_megatron_iteration
    mg_loader = MGLoaderGroupLazy.from_path(args.load_path, 0)
  File "/code/ruanwei/RLinf-online/RLinf/toolkits/ckpt_convertor/utils/mg_loader.py", line 90, in from_path
    return cls.from_file(pt_files, prefix)
  File "/code/ruanwei/RLinf-online/RLinf/toolkits/ckpt_convertor/utils/mg_loader.py", line 63, in from_file
    assert os.path.exists(pt_file), f"pt_file not exist! {pt_file}"
AssertionError: pt_file not exist! /code/ruanwei/RLinf-online/RLinf/examples/coding_online_rl/logs/online-ppo-1.5b-pipeline/checkpoints/global_step_10/actor/iter_0000010/mp_rank_01/model_optim_rng.pt
```

### Environment

python -V:
uv pip list:
nvidia-smi:
RLinf version:
Docker image tag: 

### Before submitting a new issue...

- [x] Have you checked relevant issues, FAQs (https://rlinf.readthedocs.io/en/latest/rst_source/faq.html), or asked the chatbot at the top right corner of the [documentation page](https://rlinf.readthedocs.io).

**Comment by qurakchin** [comment]
It‘s indeed strange. With tp size 2, megatron would save the weight of tp rank 2 into mp_rank_01. I will try to reproduce it later.

**Comment by qurakchin** [comment]
Hi @yuani114 , this has been addressed in #347. Thanks for your submission!

**Comment by yuani114** [comment]
> Hi [@yuani114](https://github.com/yuani114) , this has been addressed in [#347](https://github.com/RLinf/RLinf/pull/347). Thanks for your submission!

Thank you! I tried modifying the code according to #347 and the problem was resolved, but I found a new issue: I am running an online RL training session using the  simple_online_coding_client.py script to simulate client interactions. While the system successfully receives data and logs reward_scores , all other key training metrics such as advantages_mean, actor/policy_loss, final_loss, and grad_norm remain at 0 (or NaN for num_zeros_in_grad).

`Global Step:  50%|###############################5                               | 5/10 [2:30:53<1:10:42, 848.53s/it, sync_weights=0.384, step=41.9, training=41.5, inference=5.52, total_num_sequence=16, prompt_length=122, response_length=5.91e+3, total_length=6.03e+3, reward_scores=0.312, fraction_of_samples_properly_ended=1, advantages_mean=0, advantages_max=0, advantages_min=0, actor/policy_loss=0, actor/ratio=0.00096, actor/clipped_ratio=1, actor/dual_cliped_ratio=0, actor/approx_kl=0, actor/clip_fraction=0, final_loss=0, entropy_loss=0, kl_loss=0, grad_norm=0, num_zeros_in_grad=nan, lr=2e-6, update_success=1]
Global Step:  60%|#######################################                          | 6/10 [2:30:53<38:17, 574.28s/it, sync_weights=0.384, step=41.9, training=41.5, inference=5.52, total_num_sequence=16, prompt_length=122, response_length=5.91e+3, total_length=6.03e+3, reward_scores=0.312, fraction_of_samples_properly_ended=1, advantages_mean=0, advantages_max=0, advantages_min=0, actor/policy_loss=0, actor/ratio=0.00096, actor/clipped_ratio=1, actor/dual_cliped_ratio=0, actor/approx_kl=0, actor/clip_fraction=0, final_loss=0, entropy_loss=0, kl_loss=0, grad_norm=0, num_zeros_in_grad=nan, lr=2e-6, update_success=1][36m(OnlineRouterWorker pid=4663)[0m [INFO 14:30:51 OnlineRouterWorker-Rank-0][online_router_worker.py:224] Starting model synchronization...`

I also tried changing `advantages=[0.0]` to `advantages=None` in the `rollout_result = RolloutResult(...)` block within `rlinf/workers/rollout/server/server_rollout_worker.py`, but this didn't work. Could you please help me figure out what might be causing this issue and how to properly fix it? I would really appreciate your guidance on this!

**Comment by qurakchin** [comment]
Thanks, we find that in #137 we made a mistake and then the advantages computation is wrong. We will fix it soon.

**Comment by qurakchin** [comment]
Hi @yuani114 , it is fixed in #365 now. You can have a try.

**Comment by yuani114** [comment]
> Hi [@yuani114](https://github.com/yuani114) , it is fixed in [#365](https://github.com/RLinf/RLinf/pull/365) now. You can have a try.

Thanks! I have modified the code according to #365, and the advantage seems to be calculated normally. After that, I tried modifying the code in `examples/coding_online_rl/simple_online_coding_client.py` to verify the effectiveness of code online RL. For this validation, I used the dataset code-fim-v2-python-filtered_formatted_train_3k.jsonl and adopted qwen3-32b as the judge model.However, I found that the reward decreases with training, and there is no curve where the reward increases with training like GRPO in the blog. Is there a problem with my PPO settings? Or where is the problem?

<img width="2096" height="1006" alt="Image" src="https://github.com/user-attachments/assets/88f74af3-1ede-492b-8657-b34d1ebec3cd" />

<img width="2143" height="637" alt="Image" src="https://github.com/user-attachments/assets/92e2098d-acf3-4841-b687-b03a556d6acf" />

### examples/coding_online_rl/simple_online_coding_client.py

```
import asyncio
import uuid
from datetime import datetime
import pandas as pd
import httpx
import random
from typing import List, Optional, Tuple, Union
import requests


batch_size = 32
epoch = 10000000



train_count = 0

df = pd.read_json('/code/ruanwei/RLinf-online/code-fim-v2-python-filtered/code-fim-v2-python-filtered_formatted_train_3k.jsonl',lines=True)

judge_prompt = """
请你作为代码质量评估专家，对给定的代码补全结果进行质量评分。这份评分将用于强化学习训练中的奖励信号，因此请确保评分客观、一致且有区分度。

评估依据信息
<prefix>{prefix}</prefix>
<suffix>{suffix}</suffix>
<completion>{response}</completion>

信息项描述
prefix: 代码的前半部分
suffix: 代码的后半部分
completion: LLM 提供的待评估补全内容（即 Prompt 和 Suffix 之间的部分）。

评分标准如下，采用 0-10 分制，分为 5 个等级（0, 3, 6, 8, 10）：
正确性和功能性（correctness_and_functionality）：
0 分：代码完全不能实现预期功能，存在根本性逻辑错误
3 分：代码能实现部分功能，但存在严重逻辑缺陷或无法处理常见情况
6 分：代码能实现核心功能，但存在一些边缘情况处理不当或 minor 错误
8 分：代码能正确实现所有功能，仅存在极少可忽略的问题
10 分：代码完美实现所有功能，逻辑严谨，能妥善处理各种边缘情况

请基于以上标准对提供的代码补全结果进行评分，并按照以下 XML 格式输出，确保分数为指定的五个等级之一，理由简短具体且有针对性：
xml
<evaluation>
<criteria_scores>
    <correctness_and_functionality>
    <score>[SCORE]</score>
    <justification>[简短具体的理由]</justification>
    </correctness_and_functionality>
</criteria_scores>
</evaluation>

"""




async def get_llm_judge(prefix,suffix,response):
    content = await chat_completions(messages=[{'role':'user','content':judge_prompt.format(prefix=prefix, suffix=suffix, response=response)}],service_ip='my_service_ip')
    reward = 0.4
    try:
        import re
        if '</think>' in content:
            content = content.split('</think>')[-1]
        xml_match = re.search(r"<evaluation>[\s\S]*?</evaluation>", content)
        if xml_match:
            xml_str = xml_match.group(0)
            score_match = re.search(
                r"<score>\s*([0-9]+(?:\.[0-9]+)?)\s*</score>", xml_str
            )
            if score_match:
                score_val = float(score_match.group(1))
                if 0 <= score_val <= 10:
                    reward = score_val / 10.0
    except Exception:
        content = 'error'
        reward = 0.4

    return reward,content



async def agenerate(prefix, suffix):
    TARGET_URL = f"http://{service_ip}:8081/v1/completions"

    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer test-token",
    }
    body = {
        "model": "test-model",
        "prompt": f"<|fim_prefix|>{prefix}<|fim_suffix|>{suffix}<|fim_middle|>",
        "max_new_tokens": 50,
        "temperature": 0.7,
        "stream": False,
    }

    async with httpx.AsyncClient() as client:
        response = await client.post(
            TARGET_URL,
            headers=headers,
            json=body,
            timeout=120.0,
        )
    #print(f"agenerate get response: {response.json()}")
    return response.json()["choices"][0]["text"]


async def atrack(prefix, suffix, completion, accepted):
    TARGET_URL = f"http://{service_ip}:8082/api/training/submit"

    headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer test-token",
    }

    body = {
        "completionId": str(uuid.uuid4()),
        "filepath": "file:///Users/qurakchin/.vscode/extensions/continue.continue-1.2.3-darwin-arm64/continue_tutorial.py",
        "prefix": prefix,
        "suffix": suffix,
        "prompt": f"<|fim_prefix|>{prefix}<|fim_suffix|>{suffix}<|fim_middle|>",
        "completion": completion,
        "modelProvider": "openai",
        "modelName": "Qwen2.5-Coder-1.5B-Q8_0.gguf",
        "accepted": accepted,
        "timestamp": datetime.now().isoformat(),
        "time": 4294,
        "uniqueId": str(uuid.uuid4()),
        "numLines": 1,
        "cacheHit": False,
    }

    async with httpx.AsyncClient() as client:
        response = await client.post(
            TARGET_URL,
            headers=headers,
            json=body,
            timeout=60.0,
        )
        #print(f"atrack get response: {response.json()}")


async def single_iteration(prefix, suffix):
    global train_count
    #await asyncio.sleep(0.001)
    completion = await agenerate(prefix=prefix, suffix=suffix)
    #await asyncio.sleep(0.001)
    accepted,content = await get_llm_judge(prefix,suffix,completion)
    await atrack(prefix=prefix, suffix=suffix, completion=completion, accepted=accepted)
    print(f"{train_count} {accepted} {content}")
    train_count+=1

    if train_count % 100 == 0:
        print(f"train_count: {train_count}")


async def loop():



    tasks = []
    for i in range(batch_size * epoch):
        index = random.randint(0, len(df) - 1)
        prefix = df.loc[index, 'prefix']
        suffix = df.loc[index, 'suffix']
        #避免超长
        if len(prefix)>10000:
            prefix = prefix[-5000:]
        if len(suffix)>10000:
            suffix = suffix[:5000]

        
        task = asyncio.create_task(single_iteration(prefix, suffix))
        tasks.append(task)

        if i % batch_size == 0:
            await asyncio.gather(*tasks)
            tasks = []
    await asyncio.gather(*tasks)


if __name__ == "__main__":
    asyncio.run(loop())
```

### Configuration YAML file
```
defaults:
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

storage:
  storage_dir: /code/ruanwei/RLinf-online/RLinf/training_data_new

cluster:
  num_nodes: 1
  component_placement:
    # online rl must use disaggregated placement.
    rollout: 2-3
    inference: 1-1
    actor: 0-0
    reward: 2-3
runner:
  task_type: coding_online_rl
  logger:
    log_path: ${runner.output_dir}/${runner.experiment_name}
    project_name: rlinf
    experiment_name: ${runner.experiment_name}
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 60
  max_steps: -1

  val_check_interval: 1
  save_interval: 2

  seq_length: 8192

  enable_dynamic_batch_size: False
  max_tokens_per_mbs: 8192

  resume_dir: null
  experiment_name: online-ppo-1.5b-pipeline
  output_dir: /code/ruanwei/RLinf-online/RLinf/examples/coding_online_rl/logs

algorithm:
  # online rl use ppo.
  group_size: 1

  n_minibatches: 2
  training_batch_size_per_gpu: 1 # micro batch size
  rollout_batch_size_per_gpu: null # If set to null, rollout_batch_size will be evenly divided across all inference instances. You can reduce this parameter if inference consumes too much GPU memory.

  # mbs to do log prob inference, can be set to
  # lower than rollout_batch_size_per_gpu to reduce
  # memory usage
  logprob_forward_micro_batch_size: 1 # ${.rollout_batch_size_per_gpu}

  # val rollout mbs
  val_rollout_batch_size_per_gpu: 4 # ${.rollout_batch_size_per_gpu}

  recompute_logprobs: True
  shuffle_rollout: False

  max_num_gen_batches: 1

  # PPO loss params (no critic model)
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0 # 0.001
  kl_penalty_type: low_var_kl
  ratio_clip_eps: 0.2
  entropy_bonus: 0.0
  calculate_entropy: True
  clip_ratio_c: null # 3.0

  # Control critic usage (similar to AReaL's disable_head)
  use_critic: False  # Disable critic model
  use_value_loss: False  # Disable value loss computation
  
  # PPO parameters for no-critic setup
  gamma: 0.99
  gae_lambda: 0.95
  # value_clip and huber_delta not needed without critic


  # Use raw rewards as advantages
  adv_type: raw
  normalize_advantages: False
  early_stop_imp_ratio: 5.0
  use_valid_token_scale: False

  # params for rollout
  sampling_params:
    use_greedy: False
    temperature: 0.9
    top_k: 1000000
    top_p: 1.0
    repetition_penalty: 1.0
    max_new_tokens: ${subtract:${runner.seq_length}, ${data.max_prompt_length}}
    min_new_tokens: 1
    stop: [
      "<|endoftext|>",
      "<|fim_prefix|>",
      "<|fim_middle|>",
      "<|fim_suffix|>",
      "<|fim_pad|>",
      "<|repo_name|>",
      "<|file_sep|>",
      "<|im_start|>",
      "<|im_end|>",
    ]

inference:
  model_arch: ${rollout.model_arch}
  group_name: "InferenceGroup"
  load_from_actor: True
  model:
    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    sequence_parallel: False

rollout:
  group_name: "RolloutGroup"

  gpu_memory_utilization: 0.55

  model_dir: /models/Qwen/Qwen2.5-Coder-1.5B
  model_arch: qwen2.5
  precision: ${actor.model.precision} # precision for rollout model, support [fp16, bf16, fp32]  
  enforce_eager: False         # if False, rollout engine will capture cuda graph, which will take more time to initialize.
  distributed_executor_backend: mp   # ray or mp
  disable_log_stats: False
  detokenize: True            # Whether to detokenize the output.
  padding: null               # will be tokenizer.pad_token_id if null. it is used to filter megatron's padding for rollout engine
  eos: null                   # will be tokenizer.eos_token_id if null.

  rollout_backend: sglang     # online_rl now only support sglang 

  sglang:
    attention_backend: triton # [flashinfer, triton] for more, see sglang's doc
    decode_log_interval: 500000 # the interval for SGLang to log the decode time and other stats.
    use_torch_compile: False # enable torch_compile in SGLang for rollout.
    torch_compile_max_bs: 128 # the maximum batch size for torch compile. If the batch size is larger than this, torch compile will not be used.

  vllm:
    # not used, but reserved to pass config validate
    attention_backend: FLASH_ATTN #[FLASH_ATTN,XFORMERS] for more, see vllm's doc
    enable_chunked_prefill: True  # enable vllm to use chunked_prefill.
    enable_prefix_caching: True   # enable vllm to use prefix_caching.
    enable_flash_infer_sampler: True # if True, vllm will use flashinfer to do sampling.

  return_logprobs: ${not:${algorithm.recompute_logprobs}}

  tensor_parallel_size: 1
  pipeline_parallel_size: 1

  validate_weight: False # whether to send all weights at first for weight comparison.
  validate_save_dir: null # the directory to save the weights for comparison. If validate_weight is True, this will be used to save the weights for comparison.
  print_outputs: False         # whether to print the outputs (token ids, texts, etc.) of rollout engine.

  max_running_requests: 64 # the maximum number of running requests in the rollout engine.
  cuda_graph_max_bs: 128 # the maximum batch size for cuda graph. If the batch size is larger than this, cuda graph will not be used.

data:
  # not used, but reserved to pass config validate
  max_prompt_length: 1024
  rollout_batch_size: 128
  seed: 1234

actor:
  group_name: "ActorGroup"
  training_backend: megatron
  mcore_gpt: True
  spec_name: decoder_gpt

  checkpoint_load_path: null #/code/ruanwei/RLinf-online/RLinf/examples/coding_online_rl/logs/online-ppo-1.5b-pipeline/converted_ckpts/actor

  offload_optimizer: True
  offload_weight: True
  offload_grad: True

  enable_dp_load_balance: False

  calculate_flops: False

  seed: 1234

  model:
    precision: bf16
    add_bias_linear: False

    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1

    activation: swiglu
    sequence_parallel: False
    # recompute_method: block
    # recompute_granularity: selective

    recompute_method: block
    recompute_granularity: full
    recompute_num_layers: 20

    seq_length: ${runner.seq_length}
    encoder_seq_length: ${runner.seq_length}

    normalization: rmsnorm

    position_embedding_type: rope

    apply_rope_fusion: True
    bias_dropout_fusion: False
    persist_layer_norm: False
    bias_activation_fusion: False
    attention_softmax_in_fp32: True
    batch_p2p_comm: False
    variable_seq_lengths: True
    gradient_accumulation_fusion: False
    moe_token_dispatcher_type: alltoall
    use_cpu_initialization: False

  optim:
    optimizer: adam
    bf16: True
    fp16: False
    lr: 2e-06
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    min_lr: 2.0e-7
    weight_decay: 0.05
    use_distributed_optimizer: True
    overlap_grad_reduce: False
    overlap_param_gather: False
    optimizer_enable_pin: False
    overlap_param_gather_with_optimizer_step: False
    clip_grad: 0.8
    loss_scale: 65536

  lr_sched:
    lr_warmup_fraction: 0.01
    lr_warmup_init: 0.0
    lr_warmup_iters: 0
    max_lr: 2.0e-6
    min_lr: 0.0
    lr_decay_style: constant
    lr_decay_iters: 10

  tokenizer:
    tokenizer_model: ${rollout.model_dir}
    use_fast: False
    trust_remote_code: True
    padding_side: 'right'

  megatron:
    ddp_bucket_size: null
    distributed_backend: nccl # Support 'nccl' and 'gloo'
    distributed_timeout_minutes: 30
    ckpt_format: torch #torch
    use_dist_ckpt: False  #False
    tp_comm_bootstrap_backend: nccl
    tp_comm_overlap_cfg: null # tp_comm_overlap_cfg.yaml
    use_hf_ckpt: True # if true, will transfer hf model to generate megatron checkpoint and use it for training.
    use_profiler: False # if true, will enable torch profiler when training, pay attention it has influence on performance

    ckpt_convertor: # config for ckpt convertor
      model: Qwen2.5-Coder-1.5B
      model_type: null # will be set by hf model's config if null
      hf_model_path: ${rollout.model_dir} # path to the hf model
      save_path: ${runner.output_dir}/${runner.experiment_name}/converted_ckpts/actor
      use_gpu_num : 0
      use_gpu_index: null
      process_num: 16 # number of processes to use for checkpointing
      tensor_model_parallel_size: ${actor.model.tensor_model_parallel_size}
      pipeline_model_parallel_size: ${actor.model.pipeline_model_parallel_size}

    profiler: # profile megatron when inference and traning
      output_dir: ${runner.output_dir}/${runner.experiment_name}/profiler
      activities: ["cpu", "cuda"]
      record_shapes: False
      profile_memory: False
      with_stack: False
      with_flops: False
      with_modules: True
      export_tensorboard: True
      export_chrome_trace: False
      chrome_filename_prefix: "chrome_trace"
      schedule_warmup: 2
      schedule_active: 1
      schedule_repeat: 1 # inference and training will repeat such times
      # schedule_wait: it will be set at runtime

reward:
  # online rl get reward from user judge.
  use_reward_model: False

critic:
  use_critic_model: False

server:
  # online serving and user reward tracking.
  online_router:
    host: 0.0.0.0
    port: 8081

  tracking_rollout:
    host: 0.0.0.0
    port: 8082
```
